### ISSUE TITLE
if we want to do this ...

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#1]
I wish github had messaging. @mtreca - I added you to this repo just in case we wanted to do this apart from helm-bibtex. While there are downsides, there are also advantages.

Only makes sense, though, if the changes aren't added to bibtex completion (which I much prefer), so we should wait on that decision.

If we do go this direction, you could add your code, and I could add my changes on top of it.

**Comment by mtreca** [comment]
Hi @bdarcus, thanks a lot for the invitation. I am interested in collaborating for this package. I am still pretty busy at work, but I will probably take half a day this week to catch up on different threads regarding the project and think about how I could contribute best to this project. Thanks for your involvement!

**Comment by bdarcus** [comment]
Sounds good.

It looks like it will be a couple of weeks before Titus can look at our PRs, so that gives you some time too.

The key changes I made on my code are on the key --read functions.

**Comment by bdarcus** [comment]
I've decided to focus on this, more than the PR, as stuff can always be moved back, and it's just much easier to manage with a separate repo, issue tracker, etc., and without having to worry about legacy stuff.

I have a couple of open issues and PRs @mtreca, if you have any feedback.

**Comment by mtreca** [comment]
Hi again. I sadly still do not really have time on the project, but it seems that my help is not really needed at this point. Stellar work on this package! The elisp looks really clean and the whole integration with completion-read and the emabrk ecosystem is very elegant. I will be happy to test it and provide feedback.

**Comment by bdarcus** [comment]
Yeah, to bring you up-to-speed, main changes I made was to remove the macro (for simplicity and flexibility), and to switch to `completing-read-multiple`. Also, changed map to cl-loop.

**Comment by bdarcus** [comment]
Also, for what I'm working on now, see #37.
