### ISSUE TITLE
Please add autoloads

### ISSUE THREAD

**Issue by publicimageltd** [bdarcus/bibtex-actions#109]
First of all, thanks for a great package! It completes my migration to `selectrum` and allows me to finally remove helm.

When loading the package via `use-package`, I had to add a special section for predefining the interactive command:
```emacs-lisp
(use-package bibtex-actions
  :quelpa (bibtex-actions)
  :commands (bibtex-actions-open-notes) ;; that one enables lazy loading
  :bind
  (("C-x l" . bibtex-actions-open-notes)))
```
So I guess if you'd just add an autoload cookie to the interactive entry points, there'd be no need for the `:commands` part here.

**Comment by bdarcus** [comment]
No problem. 

This is my first learn-as-I-go emacs package.

I had a related question in #106.

Any insight into pros and cons?

**Comment by bdarcus** [comment]
PS - I opened a PR with what I think we need. Let me know.

**Comment by publicimageltd** [comment]
> This is my first learn-as-I-go emacs package.

I'm impressed! I, for example, did still not manage to get a decent github workflow. For example, I figure I *should* have made a PR myself, being pretty sure about what to do. So thanks for doing the hard work. :-)

I think you've done right, I'd also add an autoload cookie to every interactive function. Simply because those will be bound to keys and thus trigger the autoloading.

**Comment by bdarcus** [comment]
> I figure I _should_ have made a PR myself, being pretty sure about what to do.

If you have any feedback on the `use-package` example in the README, feel free to submit a PR ;-)

I don't use use-package directly, which is why I'm not 100% sure on it.
