### ISSUE TITLE
Add predefined searches

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#119]
Along with #118, we could support arbitrary pre-defined searches also, as supported in `ivy-bibtex` and `helm-bibtex`.

https://github.com/tmalsburg/helm-bibtex#predefined-searches

How best to do this here, given we have no common entry point command?

We might need a generic `bibtex-actions` command that can be wrapped like this; so:

``` elisp
(defun my/bib-mypubs ()
   (bibtex-actions :initial "Doe"))
```

... or simply tell users to wrap their default action command. 

But if we did this, I guess I'd need an optional initial parameter on all commands.

Any other ideas?

Though I've tried to avoid macros, maybe this would be a good candidate?

OTOH, I'm not clear how useful this feature is, given how easy it is to run a search. The example of searching for your own pubs is not a very compelling one in my view.

Maybe could be useful for things like project-related searches though?

**Comment by bdarcus** [comment]
@oantolin, @minad, @mohkale - if you have a few moments, any thoughts?

cc @apc

**Comment by apc** [comment]
Could you have something like a prefix argument that, when passed to either of the functions, prompts the user to pick from a list of predefined searches?

**Comment by bdarcus** [comment]
> Could you have something like a prefix argument that, when passed to either of the functions, prompts the user to pick from a list of predefined searches?

That would seem better from a UX perspective; no?

**Comment by oantolin** [comment]
Do the various commands that serve as entry points share the same history? If not, they should. Then you can just prepopulate the history with the predefined searches, and people can use a command to search history with completion such as `consult-history`.

**Comment by bdarcus** [comment]
> Do the various commands that serve as entry points share the same history? If not, they should. Then you can just prepopulate the history with the predefined searches, and people can use a command to search history with completion such as `consult-history`.

One of the problems I keep running up against is lack of examples of how to use these CR features. I have to dig through stackexchange and such to find nuggets.

Any pointers of where I can look for good examples of how to work with history per your (sounds like excellent) suggestion?

Maybe consult itself?

**Comment by bdarcus** [comment]
OIC - adding history is really straightforward.

I'll open a PR.
