### ISSUE TITLE
Generalize bibtex-actions-get-key-org-cite

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#140]
The `bibtex-actions-get-key-org-cite` at-point function currently only works on `citation-reference` objects and so only on a single key.

It should be enhanced to also work on `citation` objects and multiple-keys.

Note, though: the `initial-value` would need to be set to a regex of the multiple keys, while the `org-cite` follow processor (see #141) would need to a pass a list of keys to the called function.

This does lead to me wonder if #141 might better be decoupled from `bibtex-actions-at-point`.

See `org-cite-basic-goto` for an example:

https://code.orgmode.org/bzg/org-mode/src/wip-cite-new/lisp/oc-basic.el#L485

EDIT: Nicolas just now added a "key-only" optional argument to [`org-cite-get-references`](https://code.orgmode.org/bzg/org-mode/src/wip-cite-new/lisp/oc.el#L420), which should allow this @ilupin:

``` elisp
(bibtex-actions-default-action (org-cite-get-references citation keys-only))
```

**Comment by ilupin** [comment]
How about
```emacs-lisp
(defun bibtex-actions-get-key-org-cite ()
  (when-let (((eq major-mode 'org-mode))
             (elt (org-element-context)))
    (pcase (org-element-type elt)
      ('citation-reference
       (org-element-property :key elt))
      ('citation
       (string-join (org-cite-get-references elt t) "\\|")))))
```

**Comment by bdarcus** [comment]
I just remembered multiple + initial input won't work well here, because as soon as you select one, the initial-value is erased for the subsequent selections.

Why use initial-value again, instead of just directly calling the functions?
