### ISSUE TITLE
Revise bibtex-actions-read to use a dedicated dynamic completion table

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#159]
As a result of various failed efforts to work around limitations in default CRM, really fixing these problems will likely require writing a specialized dynamic completion table that does what we want. Basically, I _think_ it would mean rewriting CRM and using that instead.

See: 
https://github.com/minad/vertico/issues/59#issuecomment-861248438 
#155.

To summarize the issues with CRM:

1. terrible for long candidate strings (which we use; see https://github.com/raxod502/selectrum/issues/489)
2. initial-input inconsistency (https://github.com/minad/vertico/issues/59)
3. and in general, it just seems a poor step-child to `completing-read` (though there's probably only so much we can do about that)

So I believe this would mean writing a function to adapt crm to a) shorten that candidates strings to key in the prompt (what I was experimenting with in #155), and b) adding "initial-input" and such to all selections. I don't know how to do either ATM.

Note: one downside is it would only work with fully compliant implementations, like `icomplete-vertical` and `vertico`. It currently would not work with `selectrum`. But in mid-2021, `vertico` is looking like a better option anyway.

Maybe whether to use single or multiple should be configurable?

It's worth noting that the `completing-read-multiple` function is fairly short. The entire `crm.el` file is only about 200 LOC.

**Comment by minad** [comment]
Alternative #160

**Comment by bdarcus** [comment]
If the idea in #160 is incorporated into Consult, per that discussion, this will solve the issues with crm (and maybe others).

**Comment by bdarcus** [comment]
No longer needed with #163.
