### ISSUE TITLE
`bibtex-actions--format-citation-org` inserts malformed link when not prompting for optional args

### ISSUE THREAD

**Issue by titaniumbones** [bdarcus/bibtex-actions#162]
**Describe the bug**
If `bibtex-completion-cite-prompt-for-optional-arguments` is set to `nil`,  the inserted citation ends up with an extraneous `/`, e.g.

`[cite/:ReevesHowchilipepper2008]`

FIx is easy, just change line 199 to

`(style  (if (or (not style) (string-equal style "default")) "" (concat "/" style)))` 

or alternatively, add "default" to the final branch of the if statement in the let-binding of 'style in that same function.

**Comment by bdarcus** [comment]
Thanks!

Have you had a chance to try the new "basic" "insert processor" that Nicolas is working on?

I was thinking to revise this more along those lines.

**Comment by titaniumbones** [comment]
I tried it briefly and it's lightning fast, but from what I can tell it is still only completing on citekeys, which is not much help for me when I'm working in a field I don't know well, as is the case now.  

I do really like the interface in ivy-bibtex, which I just started using this morning actually. 

In general I think completion is a tangled nightmare in Emacs, and I can't make heads or tails of it really.

**Comment by bdarcus** [comment]
I just meant his approach, that depends on where one is at point.

**Comment by bdarcus** [comment]
Any chance a) you can just submit a PR (if not, I'll of course fix it), and b) you can test out the UI in #163 and give some feedback there?

There's possibility it will be added to Consult, depending on that feedback.

You can just run the test/run.sh script.

**Comment by titaniumbones** [comment]
Wow, I learned a lot looking through your #160 on my walk just now. School system tomorrow and I teach for 3 days before heading to the woods for 4, but if I finish my lecture tonight I'll fork bibtex-actions, do a quick or and check out yr new UI.

Completion is complicated!

On Jul. 5, 2021 6:30 p.m., bdarcus ***@***.***> wrote:
EXTERNAL EMAIL:

Any chance a) you can just submit a PR (if not, I'll of course fix it), and b) you can test out the UI in #163<https://github.com/bdarcus/bibtex-actions/pull/163> and give some feedback there?

There's possibility it will be added to Consult, depending on that feedback.

You can just run the test/run.sh script.

**Comment by bdarcus** [comment]
Given the "insert" processor I just added, should I remove this entirely?

**Comment by titaniumbones** [comment]
sorry, ran out of time  and won't likely be able to look before I go away for weekend -- I trust yr judgment. Cool you have learned so much about completion. Thx. for that message on org-list trying to summarize the insane complexity.
