### ISSUE TITLE
Make both embark-act and embark-dwim available at point

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#164]
Now that I committed the follow processor (I've opened a Doom PR to add OC support, so helpful to have that merged), back to this @ilupin:

Currently, one has to chose for `bibtex-actions-at-point` to run either the default action, or to invoke `embark-act`.

Is there a way for us to have both `bibtex-actions-embark-dwim` t (for example using the OC follow processor where it's available via `org-open-at-point`), AND be able to call `embark-act` from point and get our map options?

That would be ideal. `embark-act` and `embark-dwim` are designed to be used together, after all.

It's also a bit confusing to me, and I suspect will be to other users, that when on an org-citation, calling `embark-act` gives a menu without contextual actions.

If yes, what's involved in adding that capability?

I don't fully understand this code, so ...

_Originally posted by @bdarcus in https://github.com/bdarcus/bibtex-actions/issues/143#issuecomment-872494249_

cc @publicimageltd

**Comment by ilupin** [comment]
> It's also a bit confusing to me, and I suspect will be to other users, that when on an org-citation, calling `embark-act` gives a menu without contextual actions.
>
> If yes, what's involved in adding that capability?

Actually, they can be displayed with
```
(add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
(add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))
```

but the actions will not work because embark doesn't pass the target (i.e. citation key) to interactive commands, see https://github.com/bdarcus/bibtex-actions/pull/143#issuecomment-861282462

**Comment by ilupin** [comment]
> Is there a way for us to have both `bibtex-actions-embark-dwim` t (for example using the OC follow processor where it's available via `org-open-at-point`), AND be able to call `embark-act` from point and get our map options?

You could set `bibtex-actions-embark-dwim` to `nil` by default and only set it to `t` in the org-cite processor.

```
(org-cite-register-processor 'bibtex-actions
    :follow (lambda (_datum arg)
              (let ((bibtex-actions-embark-dwim t))
               (funcall-interactively 'bibtex-actions-at-point arg))))
```

The change below makes the prefix argument toggle `bibtex-actions-embark-dwim`, i.e.
`M-x org-open-at-point` calls `embark-dwim`
`C-u M-x org-open-at-point` shows the menu 

```diff
--- a/bibtex-actions.el
+++ b/bibtex-actions.el
@@ -595,10 +595,12 @@ With prefix, rebuild the cache before offering candidates."
   "Run the default action on citation keys found at point.
 If no citation key is found, target entries can be chosen
 interactively when `bibtex-actions-at-point-fallback' is non-nil.
-With prefix ARG, rebuild the cache before offering candidates."
+With prefix ARG, toggle `bibtex-actions-embark-dwim'."
   (interactive "P")
   (if (fboundp 'embark-dwim)
-      (let ((embark-keymap-alist '((bibtex . bibtex-actions-map))))
+      (let ((embark-keymap-alist '((bibtex . bibtex-actions-map)))
+            (bibtex-actions-embark-dwim (if arg (not bibtex-actions-embark-dwim)
+                                          bibtex-actions-embark-dwim)))
         (condition-case err
             (let ((embark-target-finders '(bibtex-actions-citation-key-at-point))
                   (embark-keymap-alist '((citation-key . bibtex-actions-buffer-map)))
@@ -620,13 +622,11 @@ With prefix ARG, rebuild the cache before offering candidates."
           (user-error
            (when (and (string-equal (error-message-string err) "No target found")
                       bibtex-actions-at-point-fallback)
-             (bibtex-actions-run-default-action
-              (bibtex-actions-read :rebuild-cache arg))))))
+             (bibtex-actions-run-default-action (bibtex-actions-read))))))
     (if-let ((keys (bibtex-actions-citation-key-at-point)))
         (funcall bibtex-actions-default-action keys)
       (when bibtex-actions-at-point-fallback
-        (bibtex-actions-run-default-action
-         (bibtex-actions-read :rebuild-cache arg))))))
+        (bibtex-actions-run-default-action (bibtex-actions-read))))))
 
 (provide 'bibtex-actions)
 ;;; bibtex-actions.el ends here

```

**Comment by bdarcus** [comment]
> .. but the actions will not work because embark doesn't pass the target (i.e. citation key) to interactive commands.

Do you know if this is a necessary limitation of Embark? 

If yes, is it worth adding an issue over there to request a fix?

> The change below makes the prefix argument toggle bibtex-actions-embark-dwim, i.e.
M-x org-open-at-point calls embark-dwim
C-u M-x org-open-at-point shows the menu.

Clever; I'll give it a try.

**Comment by ilupin** [comment]
> Do you know if this is a necessary limitation of Embark?
> 
> If no, is it worth adding an issue over there to request a fix?
> 
> But it sounds like reading Omar's answer [here](https://github.com/bdarcus/bibtex-actions/pull/143#issuecomment-860988893) the answer is yes.

I don't think there is a simple fix, because many other embark actions need to be interactively called with the target passing through the minibuffer.

**Comment by bdarcus** [comment]
Right.

So I guess at some point we might want to go back to using bibtex-completion functions there, and using some UI solution for consistent menus.

BTW, I just started #167, based on org-cite commits from today. Doesn't work yet though.

**Comment by bdarcus** [comment]
There may be another option:

I don't know if it's documented, but I believe embark in general can act on non-interactive functions.

So the option is to remove all the interactive commands, and create a single command entry point: `bibtex-actiona`.

Then could have a consistent set of action functions across buffer and minibuffer.

Obviously this would make Embark pretty much required.

WDYT?
