### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by hieutkt** [bdarcus/bibtex-actions#172]
Icons are not shown for me. See my screen shot below, which include my `use-package!` config for `bibtex-actions`.
 
![Screenshot from 2021-07-11 00-33-48](https://user-images.githubusercontent.com/16746470/125171891-e670ad00-e1e0-11eb-91d3-8934be19db06.png)

I'm using the `vertico` PR of Doom Emacs, with the `+icons` flag. `all-the-icons-completion` works fine for other commands.

**Comment by bdarcus** [comment]
I think that's because of this upstream issue #166.

**Comment by hieutkt** [comment]
That's right. Turning off the `+icons` flag fixes the problem. I was under the wrong impression that `bibtex-actions` also depends on `all-the-icons-completions`.

**Comment by hieutkt** [comment]
I'm closing this issue because duplication with #166

**Comment by bdarcus** [comment]
If you have success with getting org-cite setup, let me know if you have any feedback on https://github.com/hlissner/doom-emacs/pull/5212.

I'm actually not able ATM to get it all working correctly.

**Comment by bdarcus** [comment]
Also, same problem with this branch, which more time-critical to fix :-)

https://github.com/bdarcus/bibtex-actions/pull/171
