### ISSUE TITLE
Adding `doi` and `url` to `bibtex-completion-additional-search-fields`

### ISSUE THREAD

**Issue by hieutkt** [bdarcus/bibtex-actions#173]
Currently, `bibtex-actions--format-candidates` defines the value of `has:link` by searching for `doi` or `url` fields in each entry returned by `(bibtex-completion-candidates)`. However, by default, this function only returns `authors`, `editors`, `title`, `year`, `type`, and `key` for each entry.

So I added the relevant fields to `bibtex-completion-additional-search-field` and links are properly filtered.

```elisp
(dolist (field '(url doi))
    (add-to-list 'bibtex-completion-additional-search-fields field))
```
I think this modification should be included in `bibtex-actions.el`, or we should at least mention this in the README?

**Comment by bdarcus** [comment]
What's the value of searching for specific dois or links?

You can now search for the presence of links.

> I think this modification should be included in bibtex-actions.el, or we should at least mention this in the README?

There's a lot of configuration options in bibtex-completion. Hard to know what needs to here.

**Comment by hieutkt** [comment]
Sorry if I was not clear. I'm talking about the detection of "links" -- the purple icons shown in my screenshot. 

![image](https://user-images.githubusercontent.com/16746470/125200369-fc3faa00-e294-11eb-8de7-ebfbd60cbbc5.png)

The intended behavior is to filter for those lines when user input "has:link".

![image](https://user-images.githubusercontent.com/16746470/125200567-eb436880-e295-11eb-901c-3d209990a6c6.png)


Searching for `doi` or `url` from `(bibtex-completion-candidates)` is how it is currently being implemented in `bibtex-actions`. See [line 284-289](https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions.el#L286-L289), part of the definition of `bibtex-actions--format-candidates`.

Since `(bibtex-completion-candidates)` does not return `doi` or `url` by default (without modifying `bibtex-completion-additional-search-fields`), filter for `has:link` in `bibtex-actions-open-entry` will not return any result.

**Comment by bdarcus** [comment]
> Here's what it looks like if I don't add doi or url to bibtex-completion-additional-search-fields:

Hmm ... that's not the case on my end. I'll need to explore a bit.

**Comment by hieutkt** [comment]
See the definition for `(bibtex-completion-candidates)`

> 
> Signature
> (bibtex-completion-candidates)
> 
> Documentation
> Read the BibTeX files and return a list of conses, one for each entry.
> 
> The first element of these conses is a string containing authors,
> editors, title, year, type, and key of the entry.  This string
> is used for matching.  The second element is the entry (only the
> fields listed above) as an alist.
> 

... by default only authors, editors, title, year, type, and key of the entry are returned.

**Comment by bdarcus** [comment]
I had thought I set this in this package, but turns out now.

So we have different local configs.

I definitely think we should include something in the README about this, and include it in the example `use-package` config (which I'm also hoping to update for org-cite, BTW), and also set it in the test script.

Here's what I have, for example:

``` elisp
(setq bibtex-completion-additional-search-fields '(tags doi url journal booktitle))
```

The question beyond that is whether to include it in bibtex-actions.el, when this is a user preference.

WDYT?

Feel free to prepare a PR if you like. If not, I'll do it.

**Comment by hieutkt** [comment]
Although this is important for `bibtex-actions-open-link` to work, I think mentioning in README is better, because it involve configs in another package.

And I think it may vary with different different `bib` dialects, too. For example, for me there's a `keywords` field instead of a `tags` field, so I have to change `bibtex-actions-template-suffix` accordingly. 

(Also, with `use-package` declaration, `bibtex-actions-template-suffix` has to be configure in `:init`, not `:config`, for it to take effect. I don't know why.)

Please update the README if you see fit, so you can organize the contents by your logic. I'm just exploring so I can't say I'm confident.

**Comment by hieutkt** [comment]
Also I don't know how scoping works in emacs-lisp, so I don't know if there's a clean way to update `bibtex-completion-additional-search-fields`'s value only inside a specific function. So I'll leave this to your judgement.

**Comment by bdarcus** [comment]
Done :-)
