### ISSUE TITLE
Typos in README.org

### ISSUE THREAD

**Issue by stevenbagley** [bdarcus/bibtex-actions#181]
I think the line

`(add-to-list 'embark-keymap-alist '(citation . bibtex-actions-map-buffer))`

should be (CAPS for highlighting)

`(add-to-list 'embark-keymap-alist '(citation-KEY . bibtex-actions-BUFFER-MAP))`

**Comment by bdarcus** [comment]
Ugh. Thanks; will fix.

**Comment by bdarcus** [comment]
Fixed.

Let me know how it works for you.

**Comment by stevenbagley** [comment]
Thanks. There were two typos on that line. The second one is `citation` instead of `citation-key`.

**Comment by bdarcus** [comment]
What I get for doing these at the end of the day.

Now should be fixed.

I plan to update the test script to include these config examples, so
that these mistakes are harder to make.

**Comment by stevenbagley** [comment]
No worries. I think this is a great package.
