### ISSUE TITLE
completing-read candidates do not update on bibliography change

### ISSUE THREAD

**Issue by titaniumbones** [bdarcus/bibtex-actions#184]
**Describe the bug**
when a bibliography file changes, bibtex-completion triggers `(bibtex-completion-citations)`, which refreshes completion coandidates in bibtex-ivy (an I assume bibtex-helm as well).  THe same should happen in bibtex-actions, but does not seem to

**To Reproduce**
1. Go to an org file with #+bibliography: field, or simply set `bibtex-completion-bibliography`. 
2. add an entry to your bibtex bibliography
3. Attempt to add the new entry as a citation in an org file. On my system, the new citation does not appear as a candidate, though it will for ivy-bibtex.

5. see 3., above

**Expected behavior**
see descripiton

**Screenshots**

**Emacs version:**
recent git, 
Using recent org-mode master, as well as quelpa (that is, git) packages for bibtex-actions and citeproc-el. Using bibtex-completion from MELPA. 

**Additional context**
Let me know what else you would like from me.  thx bruce.

**Comment by bdarcus** [comment]
This isn't a bug, but a conscious decision.

I'll update this reply with details in the morning.

**Comment by titaniumbones** [comment]
Hey Bruce I initially missed your explanatory comment, sorry for delay. 

I'm going to try the file-notify-add-watch solution and see if it works for me. When I'm working on something new, I tend to be following citation chains as I write (not necessarily a great practice) so coming up with a frictionless solution is something of a priority for me. I think figuring out the relationship with the global bibliography will need to be part of this, as my main library is starting to get sizeable and  bibtex takes a while to scan it.  I'd prefer to have the update take place asynchronously in a non-blocking process, but I'm not sure how easy that is to do with Emacs in its current state.  

re: pullbib, betterbibtex already does an automatic export of my libraries -- that may not be entirely optimal, but likely it's referable to writing it out on every citation entry. I'm not sure pullbib is necessary? But will investigate.

Anyway --  I'll try to be more responsive. 

Can't believe how much progress has been made this summer.

**Comment by bdarcus** [comment]
> re: pullbib, betterbibtex already does an automatic export of my libraries -- that may not be entirely optimal, but likely it's referable to writing it out on every citation entry. I'm not sure pullbib is necessary?

Yes, because it will run `bibtex-actions-refresh` when it does update, so you don't have to think about it.

Basically, if you use Z and BBT, use that and you should be done!

**Comment by titaniumbones** [comment]
> Yes, because it will run `bibtex-actions-refresh` when it does update, so you don't have to think about it.

but IIUC I still have to call bibtex-action-xxx with a prefix argument for that to work? That still feels like a bit of cognitive load for me, whereas the file-notify-add-watch method feels completely invisible. 

have finally set up embark somewhat -- I confess the completion mechanisms in emacs take a lot of getting used to for me, but I think I'm getting the hang of it. looks pretty cool.

**Comment by bdarcus** [comment]
> but IIUC I still have to call bibtex-action-xxx with a prefix argument for that to work?

That's not my understanding. The prefix arg was added so that he could get this tool to do it automatically.
 
> have finally set up embark somewhat -- I confess the completion mechanisms in emacs take a lot of getting used to for me, but I think I'm getting the hang of it. looks pretty cool.

Which completion UI are you using? I recommend vertico, which was just added as the primary completion module for doom emacs!

**Comment by bdarcus** [comment]
Don't worry about it then; they're really similar.

**Comment by bdarcus** [comment]
Main reason why vertico is it's a bit less buggy, more actively-developed ATM, and is now in doom, with an active dev community contributing to it, and committed to its long-term success.

**Comment by bdarcus** [comment]
Implemented; see the bibtex-actions-filenotify file.
