### ISSUE TITLE
Support non-PDF files in "bibtex-completion-library-path"

### ISSUE THREAD

**Issue by salutis** [bdarcus/bibtex-actions#188]
I have, for instance, the following `.bib` entry:

```
@Misc{monet-1877a,
  author       = {Claude Monet},
  title        = {La Gare Saint-{Lazare}},
  year         = 1877,
  type         = {painting},
  publisher    = {Musée d'Orsay, Paris, France}
}
```

The `.bib` entry has a corresponding `monet-1877a.jpg` file.

When I use `bibtex-actions-open`, instead of seeing the painting, I am informed that:

```
Wrong type argument: stringp, nil
```

**Comment by bdarcus** [comment]
That's a bug in bibtex-completion, which that command uses.

It should either open it, or give a useful error report.

Good luck!

**Comment by salutis** [comment]
@bdarcus As a user, where can I ask about this?

**Comment by bdarcus** [comment]
Sorry; here:

https://github.com/tmalsburg/helm-bibtex

**Comment by bdarcus** [comment]
PS - have you had a chance to try org-cite yet?

**Comment by salutis** [comment]
@bdarcus Not yet. I am waiting for the release (into `master`, a.k.a. Emacs 28). For now, I am using Pandoc.

**Comment by salutis** [comment]
@bdarcus Once `org-cite` is out, will `helm-bibtex` still be used? I have no idea how this tremendous patchwork works under the hood. (I thought I do not use Helm.) Basically, I want to be able to open JPG, PDF, HTML, ePub, or even a directory based on the key.

**Comment by salutis** [comment]
All right, I asked over at https://github.com/tmalsburg/helm-bibtex/issues/383.

**Comment by bdarcus** [comment]
Just to explain, helm-bibtex, ivy-bibtex, and his package are all front-ends for the same backend bibtex-completion code.

Usually when something breaks here it's a general problem; like completion doesn't work or something.

**Comment by salutis** [comment]
> Just to explain, `helm-bibtex`, `ivy-bibtex`, and this package are all front-ends to the same backend `bibtex-completion` code.
> 
> Usually when something breaks here it's a general problem; like completion doesn't work or something.

But then, why is the problem in `helm-bibtex` (which is just another front-end) and not some `bibtex-completion` package? Is that because that `bibtex-completion` is coupled with `helm-bibtex` for historical reasons?

**Comment by bdarcus** [comment]
> Is that because that `bibtex-completion` is coupled with `helm-bibtex` for historical reasons?

This.

It started as helm-bibtex, an intergrated package.

Then someone wanted an ivy front-end, so it basically split in three.

I agree he should change the repo name.

**Comment by salutis** [comment]
@bdarcus Thank you so much for the explanation. It would have taken me ages to figure this out on my own.
