### ISSUE TITLE
support actions on Google Scholar?

### ISSUE THREAD

**Issue by ErnestDong** [bdarcus/bibtex-actions#192]
In org-ref there's a hydra when I hit return key. Then I can search the article in Google Scholar or Web of Science. Could you support such functions? Thank you!

**Comment by bdarcus** [comment]
I think so. It has a number of other options, though; so if we add this, we should support more than just GS' right?

**Comment by bdarcus** [comment]
Actually, you might be interesting in this WIP new project.

https://github.com/jkitchin/org-ref-cite

It will be possible use its hydra menu and commands with bibtex-actions in org-mode.

Looking at how he implements this functionality, it might be better to just rely on that.

How are you using bibtex-actions currently? With what setup, in what mode(s)?

**Comment by ErnestDong** [comment]
thank you for your patience

I just started to try vertico in doom. Your awesome package support the cite grammar in org so I wanna try. I used to write essays with the help of org-ref.

**Comment by bdarcus** [comment]
Are you aware of this?

https://github.com/hlissner/doom-emacs/pull/5290

My plan is to make it easy for people use the embark-based actions in buffer I have here, or the hydra-based approach John takes. Should work.

**Comment by ErnestDong** [comment]
Thank you! I'll try

**Comment by bdarcus** [comment]
I'm still trying to figure out some things, so it may not work correctly ATM :-)

**Comment by bdarcus** [comment]
Here's doom, vertico, bibtex-actions, but org-cite-ref hydra for the "follow processor":

![Screenshot from 2021-07-26 11-45-19](https://user-images.githubusercontent.com/1134/127019127-b3a01e54-800a-4ef0-a9c7-e9b2f3ac6595.png)

**Comment by ErnestDong** [comment]
wow, awesome

**Comment by bdarcus** [comment]
FYI, here's a better way to hook in related online search commands, though for now I don't think I'll include it.

https://github.com/bdarcus/citar/wiki/Embark#embark-become
