### ISSUE TITLE
Problem with bibtex-completion-format-citation-functions

### ISSUE THREAD

**Issue by mclearc** [bdarcus/bibtex-actions#198]
**Describe the bug**
I've got `bibtex-completion-format-citation-functions` set as follows:

```emacs-lisp
  (setq bibtex-completion-format-citation-functions
        '((org-mode      . bibtex-completion-format-citation-org-cite)
          (latex-mode    . bibtex-completion-format-citation-cite)
          (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
          (default       . bibtex-completion-format-citation-pandoc-citeproc)))
```

However, when I use `bibtex-actions-insert-key` I only get the default insert action (i.e. I get "key" inserted rather than "[cite:@key]". This may be a configuration issue. But I've found it difficult (to put it mildly) to get citations working with the new org-cite/oc packages and bibtex-actions. 

**Emacs version:**
emacs 28 on macOS Catalina 10.14.7

**Additional context**
I'm using the most recent version of bibtex-actions and related packages (i.e. bibtex-completion, citeproc, oc, etc.)

**Comment by bdarcus** [comment]
I'll look into it.

But if you're focused on org-cite, use oc-bibtex-actions and `org-cite-insert`; much better experience.

More later.

**Comment by bdarcus** [comment]
BTW, after you have a chance to try that, I was actually thinking to remove that function.

WDYT?

**Comment by mclearc** [comment]
Thanks for such a quick response (and, I should say, for all the work you've been doing in the emacs citation ecosystem). I can report that oc-bibtex-actions and org-cite-insert work for me. Is the idea that I should be configuring oc-bibtex-actions *rather than* bibtex-actions in a use-package setup? Right now I have both (plus oc,  citeproc, and bibtex-completion). I'll put the whole thing below just in case this really does end up being a config bug on my part.

```emacs-lisp
 ;;;; Citeproc
(use-package citeproc
  :straight (:host github
             :repo "andras-simonyi/citeproc-el"
             :branch "1-biblatex_support")
  :defer t
  :config
  (setq org-cite-csl-styles-dir "~/.local/share/csl/styles")
  (setq org-cite-csl-locales-dir "~/.local/share/csl/locales"))

;;;; Bibtex Completion
;; The backend of helm-ivy bibtex
(use-package bibtex-completion
  :straight (bibtex-completion :host github :repo "tmalsburg/helm-bibtex" :files (:defaults (:exclude "helm-bibtex.el" "ivy-bibtex.el")) :includes oc-bibtex-actions)
  :config
  ;; Library paths
  (setq bibtex-completion-bibliography cpm-bibliography
        bibtex-completion-library-path "~/Library/Mobile Documents/iCloud~com~sonnysoftware~bot/Documents/be-library"
        bibtex-completion-pdf-field nil
        bibtex-completion-notes-path "~/Dropbox/Work/projects/notebook/content-org"
        bibtex-completion-notes-extension ".org")
  ;; using with org-cite
  ;; make sure to set this to ensure open commands work correctly
  (setq bibtex-completion-additional-search-fields '(doi url)))

;;;; Org-Cite
;; Eventually this should be a full replacement of org-ref
(use-package oc
  :after org
  (setq org-cite-global-bibliography cpm-bibliography)
  (setq org-cite-export-processors
        '((beamer natbib)
          (latex biblatex)
          (t csl))))

;; Org-cite processors
(use-package oc-basic
  :straight nil
  :after oc)

(use-package oc-biblatex
  :straight nil
  :after oc)

(use-package oc-csl
  :straight nil
  :after oc
  :config
  ;; optional; add to docs instead?
  (setq org-cite-csl-styles-dir "~/.local/share/csl/styles")
  (setq org-cite-csl-locales-dir "~/.local/share/csl/locales"))

(use-package oc-natbib
  :straight nil
  :after oc)

;;;; Bibtex-Actions
;; Use completing read to select bibtex actions
(use-package bibtex-actions
  :after bibtex-completion
  :straight (:host github :repo "bdarcus/bibtex-actions" :includes oc-bibtex-actions)
  :commands (bibtex-actions-open
             bibtex-actions-open-pdf
             bibtex-actions-open-link
             bibtex-actions-insert-citation
             bibtex-actions-insert-reference
             bibtex-actions-insert-bibtex
             bibtex-actions-add-pdf-attachment
             bibtex-actions-open-notes
             bibtex-actions-open-entry
             bibtex-actions-add-pdf-to-library)
  :general
  (cpm/leader-keys
    "ux" 'bibtex-actions-insert-key)
  :custom
  (bibtex-actions-template '((t . "${author:15}   ${title:40}   ${year:4}")))
  (bibtex-actions-template-suffix '((t . "   ${=key=:15}  ${=type=:12}    ${tags:*}")))
  :config

  ;; Library paths
  (setq bibtex-completion-bibliography cpm-bibliography
        bibtex-completion-library-path "~/Library/Mobile Documents/iCloud~com~sonnysoftware~bot/Documents/be-library"
        bibtex-completion-pdf-field nil
        bibtex-completion-notes-path "~/Dropbox/Work/projects/notebook/content-org"
        bibtex-completion-notes-extension ".org")

  ;; Set insert citekey with markdown citekeys for org-mode
  ;; FIXME -- org-mode citation isn't working the way I want it to
  (setq bibtex-completion-format-citation-functions
        '((org-mode      . bibtex-completion-format-citation-org-cite)
          (latex-mode    . bibtex-completion-format-citation-cite)
          (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
          (default       . bibtex-completion-format-citation-pandoc-citeproc)))

  ;; Make the 'bibtex-actions' bindings and targets available to `embark'.
  (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
  (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
  (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))
  ;; (with-eval-after-load 'embark
  ;;   (setf (alist-get 'bibtex embark-keymap-alist) 'bibtex-actions-map))

  ;; using with org-cite
  ;; make sure to set this to ensure open commands work correctly
  (setq bibtex-completion-additional-search-fields '(doi url keywords)))

(use-package oc-bibtex-actions
  :after (oc bibtex-actions)
  :config
  (setq org-cite-insert-processor 'oc-bibtex-actions
        org-cite-follow-processor 'oc-bibtex-actions)
  (setq bibtex-completion-format-citation-functions
        '((org-mode      . bibtex-completion-format-citation-org-cite)
          (latex-mode    . bibtex-completion-format-citation-cite)
          (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
          (default       . bibtex-completion-format-citation-pandoc-citeproc))))

```

**Comment by bdarcus** [comment]
I'm not great with use-package, but oc-bibtex-actions requires
bibtex-actions, so I think can just configure the former?

**Comment by bdarcus** [comment]
I am trying to figure this all out here, though, for integration with Doom:

https://github.com/hlissner/doom-emacs/pull/5290

**Comment by mclearc** [comment]
Yeah -- I've been trying to monitor what you've been doing there and translate it accordingly. `org-cite-insert` works well for me so long as `oc-bibtex-actions` has been loaded properly. Otherwise it hangs forever. So I'm just trying to figure out the right load configuration (especially since I tend to defer loading all packages as much as possible). I would also like to be able to configure the bibtex-completion package settings separately rather than repeat them in bibtex-actions, but that hasn't quite been working right for some reason.

**Comment by bdarcus** [comment]
BTW, I see you're testing the biblatex branch at citeproc-el. Make sure you get him feedback, if you have any, so he can get it merged, etc.

**Comment by bdarcus** [comment]
> So I'm just trying to figure out the right load configuration (especially since I tend to defer loading all packages as much as possible). I would also like to be able to configure the bibtex-completion package settings separately rather than repeat them in bibtex-actions, but that hasn't quite been working right for some reason.

I'm thinking Henrik will set me straight in the end :-)

**Comment by mclearc** [comment]
just FYI -- the following config works well in terms of load order, though I am still not seeing `bibtex-completion-format-citation-functions` work quite as expected, e.g., in markdown files and org files both I get "key" instead of (markdown) "[@key]" and (org) "[cite:@key]". However, `org-cite-insert` works great in org, so long as I have `oc-bibtex-actions` loaded prior to calling it. Otherwise it hangs.

```emacs-lisp
;;; Bibliography files
(defvar cpm-bibliography '("~/Dropbox/Work/bibfile.bib"))

;;; Citations
;;;; Org-Cite
;; Eventually this should be a full replacement of org-ref
(use-package oc
  :after org
  (setq org-cite-global-bibliography cpm-bibliography)
  (setq org-cite-export-processors
        '((beamer natbib)
          (latex biblatex)
          (t csl))))

;; Org-cite processors
(use-package oc-basic
  :straight nil
  :after oc)

(use-package oc-biblatex
  :straight nil
  :after oc)

(use-package oc-csl
  :straight nil
  :after oc
  :init
  ;; optional; add to docs instead?
  (setq org-cite-csl-styles-dir "~/.local/share/csl/styles")
  (setq org-cite-csl-locales-dir "~/.local/share/csl/locales"))

(use-package oc-natbib
  :straight nil
  :after oc)

;;;; Citeproc
(use-package citeproc
  :straight (:host github
             :repo "andras-simonyi/citeproc-el"
             :branch "1-biblatex_support")
  :after (oc oc-csl))

;;;; Bibtex Completion
;; The backend of helm-ivy bibtex
;; Needed for the other packages
(use-package bibtex-completion
  :straight (bibtex-completion :host github :repo "tmalsburg/helm-bibtex" :files (:defaults (:exclude "helm-bibtex.el" "ivy-bibtex.el")) :includes oc-bibtex-actions)
  :after (:any org markdown)
  :init
  ;; Library paths
  (setq bibtex-completion-bibliography cpm-bibliography
        bibtex-completion-library-path "~/Library/Mobile Documents/iCloud~com~sonnysoftware~bot/Documents/be-library"
        bibtex-completion-pdf-field nil
        bibtex-completion-notes-path "~/Dropbox/Work/projects/notebook/content-org"
        bibtex-completion-notes-extension ".org")
  ;; using with org-cite
  ;; make sure to set this to ensure open commands work correctly
  (setq bibtex-completion-additional-search-fields '(doi url keywords))

  ;; Notes templates
  (setq bibtex-completion-notes-template-one-file "* ${author} (${date}): ${title} \n :PROPERTIES:\n :INTERLEAVE_PDF: ${file}\n :Custom_ID: ${=key=}\n :END:\n [[pdfview:${file}][file link]]")
  (setq bibtex-completion-notes-template-multiple-files "#+TITLE: ${author-or-editor} (${year}): ${title}\n#+ROAM_KEY: cite:${=key=}\n#+SETUPFILE: ./hugo_setup.org\n#+HUGO_SECTION: reading-notes\n\n- Tags :: \n- Bookends link :: bookends://sonnysoftware.com/${beref}\n- PDF :: [[${file}][PDF Link]]\n\n#+BEGIN_SRC bibtex\n (insert (org-ref-get-bibtex-entry \"${=key=}\"))\n#+END_SRC")

  ;; Set insert citekey with markdown citekeys for org-mode
  ;; FIXME -- org-mode citation isn't working the way I want it to
  (setq bibtex-completion-format-citation-functions
        '((org-mode      . bibtex-completion-format-citation-org-cite)
          (latex-mode    . bibtex-completion-format-citation-cite)
          (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
          (default       . bibtex-completion-format-citation-pandoc-citeproc))))

;;;; Bibtex-Actions
;; Use completing read to select bibtex actions
(use-package bibtex-actions
  :after bibtex-completion
  :demand t
  :straight (:host github :repo "bdarcus/bibtex-actions" :includes oc-bibtex-actions)
  :commands (bibtex-actions-open
             bibtex-actions-open-pdf
             bibtex-actions-open-link
             bibtex-actions-insert-citation
             bibtex-actions-insert-key
             bibtex-actions-insert-reference
             bibtex-actions-insert-bibtex
             bibtex-actions-add-pdf-attachment
             bibtex-actions-open-notes
             bibtex-actions-open-entry
             bibtex-actions-add-pdf-to-library)
  :custom
  (bibtex-actions-template '((t . "${author:15}   ${title:40}   ${year:4}")))
  (bibtex-actions-template-suffix '((t . "   ${=key=:15}  ${=type=:12}    ${tags:*}")))
  :config
  ;; use icons
  (setq bibtex-actions-symbols
        `((pdf . (,(all-the-icons-icon-for-file "foo.pdf" :face 'all-the-icons-dred) .
                  ,(all-the-icons-icon-for-file "foo.pdf" :face 'bibtex-actions-icon-dim)))
          (note . (,(all-the-icons-icon-for-file "foo.txt") .
                   ,(all-the-icons-icon-for-file "foo.txt" :face 'bibtex-actions-icon-dim)))
          (link .
                (,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'all-the-icons-dpurple) .
                 ,(all-the-icons-faicon "external-link-square" :v-adjust 0.02 :face 'bibtex-actions-icon-dim)))))
  ;; Here we define a face to dim non 'active' icons, but preserve alignment
  (defface bibtex-actions-icon-dim
    '((((background dark)) :inherit bespoke-highlight)
      (((background light)) :inherit bespoke-highlight))
    "Face for obscuring/dimming icons"
    :group 'all-the-icons-faces)

  ;; don't autopopulate initial input
  (setq bibtex-actions-initial-inputs
        '((pdf    . nil)
          (note   . nil)
          (link   . nil)
          (source . nil)))


  ;; Make the 'bibtex-actions' bindings and targets available to `embark'.
  (with-eval-after-load 'embark
    (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
    (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
    (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map)))
  ;; (with-eval-after-load 'embark
  ;;   (setf (alist-get 'bibtex embark-keymap-alist) 'bibtex-actions-map))

  ;; using with org-cite
  ;; make sure to set this to ensure open commands work correctly
  (setq bibtex-completion-additional-search-fields '(doi url keywords)))

(use-package oc-bibtex-actions
  :after (:any oc bibtex-actions)
  :demand t
  :commands (oc-bibtex-actions-select-style)
  :general
  (cpm/leader-keys
    "ux" 'org-cite-insert)
  :config
  (setq org-cite-insert-processor 'oc-bibtex-actions
        org-cite-follow-processor 'oc-bibtex-actions))

```

**Comment by bdarcus** [comment]
Can you look at this and tell me why I'm not getting bibtex-actions for `org-cite-insert`?

https://github.com/hlissner/doom-emacs/blob/5e4f92cd899e51530090f6db28cf3b5a91df1b5b/modules/tools/biblio/config.el

I assume it's load-order related, but not sure.

BTW, I removed initial-input support over the weekend, so you can remove those lines.

**Comment by bdarcus** [comment]
Actually, I'll your oc-bibtex-actions.

**Comment by bdarcus** [comment]
One other thing: you should need to have those commands lines, as the commands are auto-loaded?

**Comment by mclearc** [comment]
I can't say for sure why the doom commands aren't working, since I don't know for sure how the macro works. I've noticed that, for whatever reason, the ":commands" autoloading for `oc-bibtex-actions` isn't working properly. The command isn't available until the package (file) itself has been loaded.

**Comment by mclearc** [comment]
FYI -- this is the expanded part of the use-package macro for that ":commands" field:

```emacs-lisp
        (progn
          (setq org-cite-insert-processor 'oc-bibtex-actions org-cite-follow-processor 'oc-bibtex-actions)
          t)
```

**Comment by mclearc** [comment]
Here's the minimal expansion of `oc-bibtex-actions`:

```emacs-lisp
(progn
  (straight-use-package 'oc-bibtex-actions)
  (defvar use-package--loaded249 nil)
  (defvar use-package--result249 nil)
  (defvar use-package--next249
    (function
     (lambda nil
       (if use-package--loaded249 use-package--result249
         (setq use-package--loaded249 t use-package--result249
               (progn
                 (require 'oc-bibtex-actions nil nil)
                 (setq org-cite-insert-processor 'oc-bibtex-actions org-cite-follow-processor 'oc-bibtex-actions)
                 t
                 (cpm/leader-keys "ux" 'org-cite-insert :package 'oc-bibtex-actions)))))))
  (eval-after-load 'oc
    '(funcall use-package--next249))
  (eval-after-load 'bibtex-actions
    '(funcall use-package--next249)))
```

For some reason the `:commands (oc-bibtex-actions-select-style)` isn't showing up properly.

**Comment by bdarcus** [comment]
So where do we stand @mclearc? Any objection to me removing this function in favor of `oc-bibtex-actions`?

I wrote that before the org-cite "insert" functionality existed, and before bibtex-completion got it's own org-cite function.

Also, this may be related, but can you take a look at #199? That user gets error when running the default actions, mine just doesn't work ATM. :shrug:

**Comment by mclearc** [comment]
So is the idea that you'll get rid of `bibtex-actions-insert-key` and just have specific actions for non-org buffers (so something like `bibtex-actions-insert-md-key`)? That's the only downside I see to getting rid of the function. Or maybe I'm just misunderstanding you here? 

I'll look at #199  -- my sense is that load order is the key here. I had a similar experience as that reported by @oatmealm [here](https://github.com/bdarcus/bibtex-actions/pull/199#issuecomment-889250268). I think you need to demand oc-bibtex-actions be loaded after oc and bibtex-actions (like so; modulo whatever the doom macros are):

```emacs-lisp
(use-package oc-bibtex-actions
  :after (:any oc bibtex-actions)
  :demand t)
```

**Comment by bdarcus** [comment]
> So is the idea that you'll get rid of `bibtex-actions-insert-key`

No, no!

Maybe I was misunderstanding you, but I thought your issue was only with the org-cite piece of that? That's what I'm proposing to remove; e.g this:

https://github.com/bdarcus/bibtex-actions/blob/4c6aa3612da91e9de27687bb2a7aeb4999ca84f5/bibtex-actions.el#L199

> I think you need to demand oc-bibtex-actions be loaded after oc and bibtex-actions.

Will try; thank you!

**Comment by bdarcus** [comment]
Actually, I probably did misunderstand you; too many balls in the air ATM :-)

**Comment by mclearc** [comment]
> No, no!
> 
> Maybe I was misunderstanding you, but I thought your issue was only with the org-cite piece of that? That's what I'm proposing to remove; e.g this:

Ah got it! That makes much more sense :) So yes --- seems like you can get rid of that function in favor of `org-cite-insert`, which works perfectly for me in org files.

**Comment by oatmealm** [comment]
I was able to sort out the loading order and get the required vars set correctly before invoking any `oc` commands by adding this to 'biblio/config.el`:

``` 
(use-package! bibtex-actions
  :when (featurep! :completion vertico)
  :after embark bibtex-completion
  :config
  (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map)))
```

and 

```
(use-package! oc
  :after org bibtex-completion
  :config
  (setq org-cite-global-bibliography bibtex-completion-bibliography)
  ;; setup export processor; default csl/citeproc-el, with biblatex for latex
  (setq org-cite-export-processors
        '((latex natbib)
          (t csl))))
```

Also, when I first tried the default action, this time I was asked which of the multiple keys, but then got the same error `concat: Wrong type argument: stringp, citation-key` ... 

For reminder, I'm setting them all with this value "/home/[user]/Nextcloud/Library/references.bib" ...

**Comment by bdarcus** [comment]
> Also, when I first tried the default action, this time I was asked which of the multiple keys, but then got the same error `org-cite-list-bibliography-files: Wrong type argument: listp, "/home/uri/Nextcloud/Library/references.bib"` which I guess means it needs to be a list of string?

Yes, I had in mind to fix this.

Bibtex-completion accepts string or list of strings, but org-cite only list.

Will be easy to fix.

**Comment by bdarcus** [comment]
> I was able to sort out the loading order and get the required vars set correctly before invoking any `oc` commands by adding this to 'biblio/config.el`:

So you didn't need `:demand t`, as @mclearc suggested?

**Comment by mclearc** [comment]
I was thinking that the demand. call is required only if you're automatically deferring everything. I assumed that this is what doom does but maybe that's not right.

**Comment by bdarcus** [comment]
> I was thinking that the demand. call is required only if you're automatically deferring everything. I assumed that this is what doom does but maybe that's not right.

No, you're right; they're religious about only loading what needs to be loaded.

**Comment by bdarcus** [comment]
OK, I pushed the commit to hopefully fix both issues. When you get a chance, can you confirm @oatmealm, and maybe post on that PR?

**Comment by bdarcus** [comment]
Actually, `:demand t` alone doesn't solve it :-(

Will take a closer look at what @oatmealm came up with.

**Comment by mclearc** [comment]
> Actually, `:demand t` alone doesn't solve it :-(
> 
> 
> 
> Will take a closer look at what @oatmealm came up with.
> 
> 
> 
> Edit: actually, @oatmealm, I don't see your config for oc-bibtex-actions; isn't that the issue, since for me at least it's the one that isn't loading?

Hmm that surprises me since I also defer loading as much as possible and my setup works fine

**Comment by bdarcus** [comment]
> Hmm that surprises me since I also defer loading as much as possible and my setup works fine

Me too.

But I've had some weird things happen with my Emacs the past couple days, so maybe just me.

I'm thinking ideally we update the test script(s) to use the same use-package config as the README, so can make sure to get this right.

Not sure how straightforward that is now, before org 9.5 is officially released though.

**Comment by bdarcus** [comment]
> But I've had some weird things happen with my Emacs the past couple days, so maybe just me.

Actually, I upgraded and rebooted Emacs, and it seems to work correctly now. I also tested the path issue, and that seems to work too.

**Comment by bdarcus** [comment]
Actually, this issue still isn't solved with loading oc-bibtex-actions.

I do observe something that should narrow it down though:

 If I first do `M-x bibtex-actions-insert-key`, and then `org-cite-insert`, only then is it loaded.

But adding this doesn't not fix it:

```elisp
  :commands (oc-bibtex-actions-insert oc-bibtex-actions-select-style)
```

**Comment by mclearc** [comment]
I'm a little confused as to which problem you're tracking. One issue (the issue originally raised by me here) is that calling
`bibtex-actions-insert-key` inserts only a plain citekey (e.g. kitcher2011). But it should inset a key according to the setting in `bibtex-completion-format-citation-functions`, which I have set, in markdown, to pandoc citekey (so [@kitcher2011]) and in org to org-cite (so [cite:@kitcher2011]. Currently only calling `org-cite-insert` in an org file works reliably.

A second issue is the loading order thing. This is more doom specific. My guess is that you should just demand everything explicitly and then slowly work your way back to minimum demand requirements.

Sorry if I've gotten confused about what's going on here....¯\_(ツ)_/¯

**Comment by bdarcus** [comment]
Sorry, for the confusion. With the second message, I was trying to bring this back to your original issue.

What I'm saying on that is that's not something I have any control over. The _bibtex-completion-format-**citation**-functions_ are functions that govern `bibtex-completion-insert-citation` (not key), and so `bibtex-actions-insert-citation`.

E.g. you're using the wrong command.

Have you tried using `bibtex-actions-insert-citation` instead?

The second issue isn't Doom specific; it's just use-package stuff.  But I'll figure it out.

**Comment by mclearc** [comment]
> E.g. you're using the wrong command.

Ack! -- thanks! 🤦  I can confirm that works. 

As for loading, I demand bibtex-actions after bibtex-completion loads, and I defer the latter loading until I've loaded either markdown or org. Both citeproc and org-cite are loaded after org loads. Do you have a sense if things are loading for you in roughly that order?

**Comment by bdarcus** [comment]
> Do you have a sense if things are loading for you in roughly that order?

I'll double-check.

The interesting thing I realize today was if I run a bibtex-actions command first, and then `org-cite-insert`, `bibtex-actions-read` will load correctly.
