### ISSUE TITLE
org-cite configuration in readme

### ISSUE THREAD

**Issue by ebouna** [bdarcus/bibtex-actions#209]
The first line of code in the configuration recommend for Org-Cite in the README is: 
`(my/bibs '("~/bib/references.bib"))`

I wonder whether this shouldn't rather be `(setq my/bibs '("~/bib/references.bib"))`. Otherwise when starting emacs, I get the error message `Symbol's function definition is void: my/bibs`.
I  have Org-Mode installed from the git repository.

Thanks for your help in advance.

**Comment by bdarcus** [comment]
Yes, sorry about that.

I'm working on some changes that I think will simplify that.

**Comment by ebouna** [comment]
Thanks a lot! I'll try it out right now.

**Comment by ebouna** [comment]
Unfortunately, the issue seems to stay the same. I changed my configuration by replacing the Org-cite config part as given in the readme with the code above. The entire Bibtex-actions configuration looks like this now: 

```elisp
;;=======Bibtex-actions configuration====================
;;===Basic config===
(use-package bibtex-actions
  :bind (("C-c b" . bibtex-actions-insert-citation)
         :map minibuffer-local-map
         ("M-b" . bibtex-actions-insert-preset))
  :config
  ;; make sure to set this to ensure open commands work correctly
  (bibtex-completion-additional-search-fields '(doi url))
  (bibtex-completion-bibliography '("~/bib/references.bib")))
  
  ;;===Embark config===
(use-package bibtex-actions
  :bind (("C-c b" . bibtex-actions-insert-citation)
         :map minibuffer-local-map
         ("M-b" . bibtex-actions-insert-preset))
  :after embark
  :config
  ;; Make the 'bibtex-actions' bindings and targets available to `embark'.
  (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
  (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
  (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))
  ;; Make sure to set this to ensure 'bibtex-actions-open-link' command works correctly.
  (bibtex-completion-additional-search-fields '(doi url))
  (bibtex-completion-bibliography '("~/bib/references.bib")))

;; use consult-completing-read for enhanced interface
(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)

;;===Org-cite config===
(use-package bibtex-actions
  :after (bibtex-completion)
  :config
  (setq bibtex-completion-bibliography '("~/bib/references.bib")))

(use-package oc
  :after (org bibtex-completion)
  :config
  (setq org-cite-global-bibliography
        (let ((paths bibtex-completion-bibliography))
          ;; Always return bibliography paths as list for org-cite.
          (if (stringp paths) (list paths) paths))))

(use-package oc-basic :after oc)

(use-package oc-bibtex-actions
  :after (oc bibtex-actions)
  :demand t
  :config
  (setq org-cite-insert-processor 'oc-bibtex-actions
        org-cite-follow-processor 'oc-bibtex-actions
        org-cite-activate-processor 'basic))

;;===Additional settings===
;; Use consult-completing-read for enhanced interface.
(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)

;;If you prefer to have the embark menu open with org-open-at-point, you should set this variable:
(setq bibtex-actions-at-point-function 'embark-act)
```
So when I open an org-file and call `bibtex-actions-insert-citation` (via M-x) or `bibtex-actions-open` or `bibtex-actions-insert-key`, I immediately get the message `Symbol’s function definition is void: consult-completing-read-multiple`

**Comment by bdarcus** [comment]
> ... when I open an org-file and call `bibtex-actions-insert-citation` (via M-x) or `bibtex-actions-open` or `bibtex-actions-insert-key`, I immediately get the message `Symbol’s function definition is void: consult-completing-read-multiple`

If you want to use that, you'll need to install and configure consult; that's what that error is telling you.

You might just comment it out initially though; the "advice-add" line. Once you get it working, you can try that.

And you should use `org-cite-insert` in org.

**Comment by ebouna** [comment]
Thanks, I'll try this out, too, right now.
Actually, I did install consult, but to my init, I only added the lines of code relevant to consult that are contained in the README. But for the moment, I'll just comment out the "advice-add" line, as you suggest. 
By the way, another small detail I observed is the following:
If I remember correctly, when I added the whole Bibtex-configuration to my init file, I also had to install citeproc. So this seems to be a dependency not mentioned in the README. Is this maybe right?

**Comment by bdarcus** [comment]
Maybe right, though I am likely to remove that.

These packages are in a state of flux ATM with the release of org-cite :-)

BTW, FWIW, Doom has an excellent new vertico module that configures all this, and I'm working on a PR for org-cite.

**Comment by ebouna** [comment]
That sounds interesting.

When I call `org-cite-insert` with my org-file open, I get `Key ("" to exit): ` now.
I still would like to open a list of the keys so that I can choose from it. Is it possible to retrieve one inside org-mode? I suppose yes, but I don't know how to get it. In any event, I am not quite sure how to procede after getting `Key ("" to exit): `.

**Comment by bdarcus** [comment]
> That sounds interesting.
> 
> When I call `org-cite-insert` with my org-file open, I get `Key ("" to exit): ` now.
> I still would like to open a list of the keys so that I can choose from it. Is it possible to retrieve one inside org-mode? I suppose yes, but I don't know how to get it. In any event, I am not quite sure how to procede after getting `Key ("" to exit): `.

Making progress, but that means it's not loading the bibtex-actions UI. I've been trying to figure that out for the Doom PR.

So this isn't a solution, but try running one of the bibtex-actions commands, and then try again `org-cite-insert`.

On my system, the second time loads it correctly!

You should see something like this:

![image](https://user-images.githubusercontent.com/1134/128200073-ba2d568b-1224-4b55-997b-a83a632dcc23.png)

**Comment by ebouna** [comment]
So there is really some progress. I invoked `	bibtex-actions-insert-citation`. This allowed me for the first time to insert a citation: 
![grafik](https://user-images.githubusercontent.com/82314717/128203050-c291719a-71eb-44ee-81f9-8583c19a8a80.png)
Then I went on to call `org-cite-insert`. This now also worked the same way. But I do not get a list like you in the minibuffer. Instead the entries are displayed one by one and I have to cycle through them (my test bib  actually has only 2 entries):
![grafik](https://user-images.githubusercontent.com/82314717/128204256-8b4afce9-34fd-4548-824a-d39e3543ec06.png)

 There is also a second issue(?): when I insert 2 citations, one after the other, only the first one appears as a blue link, the second one is not a link and, thus, stays black:
![grafik](https://user-images.githubusercontent.com/82314717/128203903-7e7a60ab-ec17-4090-8439-68e910129a0f.png)

**Comment by bdarcus** [comment]
> But I do not get a list like you in the minibuffer. Instead the entries are displayed one by one and I have to cycle through them (my test bib actually has only 2 entries):

Are you sure you're in vertico there? I've not seen that.

**Comment by bdarcus** [comment]
Oh wait; I think what you may be seeing is CRM; if you're using TAB to select multiple.

If yes, this is why to use `consult--completing-read-multiple` :-)

**Comment by ebouna** [comment]
Thanks once again! I have been checking several factors that may have influence on the problems I mentioned. 

I've now understood that the issue "1st citation is a proper link, 2nd is not" was due to the fact that "org-cite-insert commands work differently depending on where point is", as you also explained above. So inserting several citations one after another know works. In addition, it is only a few moments ago that I got to know https://blog.tecosaur.com/tmio/2021-07-31-citations.html. 

I also checked the vertico issue, i.e., your question concerning vertico: I remembered I installed selectrum because you pointed out in the README that selectrum worked especially well with bibtex-actions. What I did not do was to activate selectrum in my init file. I've now added `(selectrum-mode +1)` according to the explanations on https://github.com/raxod502/selectrum (Is this also the way you activate it?) and I also activated orderless following the explanations on the same page.

Thus my list of reference entries looks like this at the moment:
![grafik](https://user-images.githubusercontent.com/82314717/128214268-0081ead5-3dae-46e0-90cf-96f6d2a2ccd0.png)

I only wonder now why in your screenshot the columns in the references list are properly indented (equally for all entries) while they are not in my case.
So are you maybe using vertico and not selectrum ?

**Comment by bdarcus** [comment]
The alignment issues are probably your font.

You (at least currently) need to use a monospaced font for consistent
alignment.

I can look into if it's possible to change that but it's not the highest
priority.

**Comment by ebouna** [comment]
Ah, ok, thanks, I see. It's the serif font. And of course, I understand that this font issue is not the highest priority.

But are you personally using then vertico and not selectrum at the moment?

**Comment by ebouna** [comment]
In org-mode, when I insert a citation with `org-cite-insert` and then hover over it, an expanded entry is shown. But, strangely enough, the year of publication is left out in this expanded entry. So I get something like "Heini, Otto. Fussball,." Note the comma - full stop at the end, where the year should be. In addition, the publishing house appears as "{Apress}". Note the brackets. Could I modify/ configure this?

**Comment by ebouna** [comment]
Yes, you're right. My .bib-file is biblatex.
(Sorry, I'm just back at work again.) 

Now there are still 2 issues: 
1) a new one I didn't have yesterday: after restarting Emacs today when I hover over an inserted entry, no expanded version is displayed anymore. In addition, where there are two inserted entries, only the 1st one now becomes green when hovering over it, whereas the 2nd one remains blue. 
(Note that as yesterday for inserting citations I've continued to first call bibtex-actions-insert-citations. Only after this, I go on using org-cite-insert.) 
2) the error: `Error (use-package): bibtex-actions/:config: Symbol’s function definition is void: bibtex-completion-additional-search-fields`: you suggested to replaced the "`:after`-line" by `:after (embark org oc bibtex-actions bibtex-completion)`. But unfortunately, I wasn't sure which "`:after`-line" of the several "`:after`-lines" in the code to correct and whether in the Org-cite configuration part or the Embark configuration part. I tried the  "`:after`-line"  following `(use-package oc-bibtex-actions` in the Org-cite configuration, but it seems this didn't change much and even caused new problems. So I'd be glad if you gave me a tip where I should best put `:after (embark org oc bibtex-actions bibtex-completion)`?

Just to be sure you are aware of the current form of my Bibtex-actions configuration in the init, I send it below again:

```elisp
;;=======Bibtex-actions configuration====================
;;===Activating selectrum, cf. https://github.com/raxod502/selectrum===
(selectrum-mode +1)

;;===Activating orderless, cf. https://github.com/raxod502/selectrum===
(setq completion-styles '(orderless))

;; Persist history over Emacs restarts
(savehist-mode)

;; Optional performance optimization
;; by highlighting only the visible candidates.
(setq orderless-skip-highlighting (lambda () selectrum-is-active))
(setq selectrum-highlight-candidates-function #'orderless-highlight-matches)


;;====Basic config====
(use-package bibtex-actions
  :bind (("C-c b" . bibtex-actions-insert-citation)
         :map minibuffer-local-map
         ("M-b" . bibtex-actions-insert-preset))
  :config
  ;; make sure to set this to ensure open commands work correctly
  (bibtex-completion-additional-search-fields '(doi url))
  (bibtex-completion-bibliography '("~/bib/references.bib")))
  
;;===Embark config===
(use-package bibtex-actions
  :bind (("C-c b" . bibtex-actions-insert-citation)
         :map minibuffer-local-map
         ("M-b" . bibtex-actions-insert-preset))
  :after embark
  :config
  ;; Make the 'bibtex-actions' bindings and targets available to `embark'.
  (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
  (add-to-list 'embark-keymap-alist '(bibtex . bibtex-actions-map))
  (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))
  ;; Make sure to set this to ensure 'bibtex-actions-open-link' command works correctly.
  (bibtex-completion-additional-search-fields '(doi url))
  (bibtex-completion-bibliography '("~/bib/references.bib")))



;;===Org-cite config===
(use-package bibtex-actions
  :after (bibtex-completion)
  :config
  (setq bibtex-completion-bibliography '("~/bib/references.bib")))

(use-package oc
  :after (org bibtex-completion)
  :config
  (setq org-cite-global-bibliography
        (let ((paths bibtex-completion-bibliography))
          ;; Always return bibliography paths as list for org-cite.
          (if (stringp paths) (list paths) paths))))

(use-package oc-basic :after oc)

(use-package oc-bibtex-actions
  :after (oc bibtex-actions)
  :demand t
  :config
  (setq org-cite-insert-processor 'oc-bibtex-actions
        org-cite-follow-processor 'oc-bibtex-actions
        org-cite-activate-processor 'basic))

;; Use consult-completing-read for enhanced interface. (The following not working, commented out so far.) 
;;(advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)

;;If you prefer to have the embark menu open with org-open-at-point, you should set this variable:
(setq bibtex-actions-at-point-function 'embark-act)
```
