### ISSUE TITLE
Symbol’s function definition is void: bibtex-completion-additional-search-fields

### ISSUE THREAD

**Issue by ebouna** [bdarcus/bibtex-actions#210]
Whenever I try to call a function, after calling it I get the error messages: 
`Error (use-package): bibtex-actions/:config: Symbol’s function definition is void: bibtex-completion-additional-search-fields`

I took the configuration as specified in the README. I have Org-mode installed from the git repository.

Thank you very much for your help with question, too.

**Comment by bdarcus** [comment]
No need to open separate issues for this, as it's another use-package config issue; a documentation issue, rather than a bug. 

I will see if I can fix these tomorrow, but in the meantime, so if changing the `:after` line as follows helps?

```elisp
:after (embark org oc bibtex-actions bibtex-completion)
```
