### ISSUE TITLE
Support for pandoc citation styles for org

### ISSUE THREAD

**Issue by oatmealm** [bdarcus/bibtex-actions#211]
Hi,

As I'm mostly interested in exporting to docx type documents via pandoc (using `ox-pandoc`) I'd like to be able to choos the citation style used when I insert a citation. Currently, citations of the style `[cite:@Memi1953]` show up in the document like so: "Memi1953:NO ITEMDATA", and if I use a prefix, I get an error `org-element-put-property: Wrong type argument: plistp, (prefix)`

I'm probably doing something wrong, but simple cites like `[[Memi1953][12]]` work just fine.

**Comment by bdarcus** [comment]
So ... this isn't really a problem here:

1. pandoc [needs to be updated to support the final org-cite syntax](https://github.com/jgm/pandoc/issues/7329)
2. you can use the native pandoc syntax if you prefer; but see the bibtex-completion documentation for how to do that

**Comment by oatmealm** [comment]
Got it. Sorry. Wasn't sure if this was confgiruable.

**Comment by oatmealm** [comment]
Mind you, `bibtex-actions` seem to take over the function list for the formatters... is this doom, or `bibtex-actions` defaults?

``
bibtex-completion-format-citation-functions is a variable defined in
bibtex-completion.el.

Value
((org-mode . bibtex-actions--format-citation-org)
 (latex-mode . bibtex-completion-format-citation-cite)
 (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
 (python-mode . bibtex-completion-format-citation-sphinxcontrib-bibtex)
 (rst-mode . bibtex-completion-format-citation-sphinxcontrib-bibtex)
 (default . bibtex-completion-format-citation-pandoc-citeproc))
```

**Comment by bdarcus** [comment]
That's me, but I actually plan to remove that org function.

**Comment by oatmealm** [comment]
Maybe you should only replace the default rather then replace everything?

https://github.com/bdarcus/bibtex-actions/blob/1119f98d5d31dc715957b6c52e6b51d59122f601/bibtex-actions.el#L115

```
(setq bibtex-completion-format-citation-functions
  '((org-mode      . bibtex-actions--format-citation-org)
    (latex-mode    . bibtex-completion-format-citation-cite)
    (markdown-mode . bibtex-completion-format-citation-pandoc-citeproc)
    (python-mode   . bibtex-completion-format-citation-sphinxcontrib-bibtex)
    (rst-mode      . bibtex-completion-format-citation-sphinxcontrib-bibtex)
    (default       . bibtex-completion-format-citation-pandoc-citeproc)))
```

**Comment by bdarcus** [comment]
This is what I'm planning:

https://github.com/bdarcus/bibtex-actions/pull/212
