### ISSUE TITLE
Embark-act at-point doesn't work

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#233]
#222 introduced a regression with `embark-act` at-point.

1. `embark-act` in buffer works as expected
2. `embark-act` at point doesn't appear to extract the key(s)
3. I don't see anywhere in this (now too big) PR where we touched the at-point code, even indirectly.

_Originally posted by @bdarcus in https://github.com/bdarcus/bibtex-actions/issues/222#issuecomment-901205094_

--------------

Minimal test files, though will only work if you have recent org master branch installed and configured:

```bibtex
@book{test1,
    title={An example title},
    author={{de Villiers}, Jane and Smith, John and Doa, Jason and Jennifer Jones},
    date={2015},
    doi={12345},
    publisher={Example Press}
}
```

```org
#+cite_export: csl
#+bibliography: test.bib

[cite:@test1]

#+print_bibliography:
#+org-cite-global-bibliography: nil
```

If you run `embark-act` while point is on the citation key and then choose `l` (open link), your browser should open, and you get a 404 error. 

What I see: nothing; just a "No link found for nil" message, which suggests the key is getting lost somewhere.

**Comment by aikrahguzar** [comment]
@bdarcus I saved the second block at `embark-test.org` and the first as `test.bib` in the same directory. `g f` on `test.bib` takes me to the file.

But call embark act with point on `@test` results or anywhere in that buffer for that matter results in `save-excursion: Search failed: "("` which is inscrutable to me.

**Comment by bdarcus** [comment]
And similar kind of thing in LaTeX; right?

**Comment by aikrahguzar** [comment]
> And similar kind of thing in LaTeX; right?

No, in latex embark find the key at point. It is just `bibtex-action` only hands it half the key probably because my keys always contain a `:`.

**Comment by bdarcus** [comment]
So if you change a key to remove the `:` it works?

It should be `bibtex-actions` code that does that; it just called the `bibtex-completion-at-point` functions.

**Comment by aikrahguzar** [comment]
> So if you change a key to remove the `:` it works?
Yes

> It should be `bibtex-actions` code that does that; it just called the `bibtex-completion-at-point` functions.
This is making me wonder if something changed in the interaction of `org` and `embark` recently.

**Comment by bdarcus** [comment]
> This is making me wonder if something changed in the interaction of `org` and `embark` recently.

Except, it worked today on an earlier commit.

**Comment by aikrahguzar** [comment]
For whatever reason it seems like the test file is too short. If I add some copied text, embark act succeeds and find the citation key
 
![2021-08-18T21:35:09,110654625+02:00](https://user-images.githubusercontent.com/88336724/129960966-8aae7a55-4a94-4a9a-a3d5-c11c62de1765.png)

**Comment by bdarcus** [comment]
But you don't have the `bibtex-actions` commands available from that menu.

You should be able to configure it like so:

```elisp
(add-to-list 'embark-keymap-alist '(oc-citation . oc-bibtex-actions-map))
```

Can you get it to run a command like `bibtex-actions-open-link`, where it gets passed the correct key?

**Comment by bdarcus** [comment]
Oh, BTW, that reminds me of something: there IS something wrong with my embark setup that I'll look into.

**Comment by aikrahguzar** [comment]
> Can you get it to run a command like `bibtex-actions-open-link`, where it gets passed the correct key, and opens the browser, as it does from the minibuffer?

No `(add-to-list 'embark-keymap-alist '(oc-citation . oc-bibtex-actions-map))` doesn't give me anything extra probably because `oc-bibtex-actions` isn't loaded. 

But even before that: does local bibliography work for `org`? Both `(bibtex-actions--local-files-to-cache)` and `(bibtex-completion-local-bibliogrpahy)` which we use internally give me `nil`.

**Comment by aikrahguzar** [comment]
Also is the problem, I thought the problem was emabrk-act not extracting the keys which it is for me.

**Comment by bdarcus** [comment]
> does local bibliography work for `org`? Both `(bibtex-actions--local-files-to-cache)` and `(bibtex-completion-local-bibliogrpahy)` which we use internally give me `nil`.

The key function to look at is `org-cite-list-bibliography-files`. That will include local ones.

But that reminds me: there's some command you can run from a buffer in emacs, where you can specify the function to call. But I forget what it is. Do you know?

And I thought we did account for that, but now I'm not sure :-)

**Comment by bdarcus** [comment]
> Also I thought the problem was emabrk-act not extracting the keys which it is for me.

Which command did you make interactive, and how, to test that?

**Comment by aikrahguzar** [comment]
> The key function to look at is `org-cite-list-bibliography-files`. That will include local ones.

Yes, that works for gives the correct bib file but not our command or bibtex-completion.

> But that reminds me: there's some command you can run from a buffer in emacs, where you can specify the function to call. But I forget what it is. Do you know?

`pp-eval-expression` bound to `SPC ;` in doom. I have been using it a lot lately for stuff like this.

> And I thought we did account for that, but now I'm not sure :-)

I distinctly remember Titus saying that `(bibtex-completion-local-bibliogrpahy)` should gives us both local and global files for org. But there is no separate path for `org` in it and I had assumed that `reftex` functions it used dealt with both latex and org. If not we need to fix the  `(bibtex-actions--local-files-to-cache)` to use `(org-cite-list-bibliography-files)`

**Comment by aikrahguzar** [comment]
> > Also I thought the problem was emabrk-act not extracting the keys which it is for me.
> 
> Which function did you make interactive, and how, to test that?

I don't have `(add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)` in my config. Before I evaluate it using `SPC ;` calling embark will treat  `cite:@test1` as a url. After evaluating it, it treat `test1` as a citation key so `bibtex-actions-citation-key-at-point` works correctly and key gets extracted correctly.

**Comment by bdarcus** [comment]
> I distinctly remember Titus saying that `(bibtex-completion-local-bibliogrpahy)` should gives us both local and global files for org. 

Yes, because it just calls `org-cite-list-bibliography-files`.

> But there is no separate path for `org` in it ...

Right, but that's why we use the diff between that and `org-cite-global-bibliography`.

**Comment by aikrahguzar** [comment]
> Yes, because it just calls `org-cite-list-bibliography-files`.

Oh, it seems like it was recent and doom hasn't updated the pin on `bibtex-completion`, which is why I don't see the path for `org` in bibtex-completion and local bib doesn't work for me in `org`.

**Comment by bdarcus** [comment]
> . After evaluating it, it treat `test1` as a citation key so `bibtex-actions-citation-key-at-point` works correctly and key gets extracted correctly.

OK, I see the same.

I also see that `oc-bibtex-actions-citation-finder` embark target finder also returns the expected (for me) result:

```elisp
(oc-citation . "kohn2013")
```

In theory, that's the last step before it gets passed to embark, and the string is what embark is expecting.

Though I can't see how, maybe it's some subtle thing that changed with the commands?

@oantolin - any tips on how to debug this? Or did something change with embark at-point stuff recently?

**Comment by bdarcus** [comment]
> > Yes, because it just calls `org-cite-list-bibliography-files`.
> 
> Oh, it seems like it was recent and doom hasn't updated the pin on `bibtex-completion`, which is why I don't see the path for `org` in bibtex-completion and local bib doesn't work for me in `org`.

IIRC, I did update the pin in the 5290 PR.

**Comment by aikrahguzar** [comment]
> IIRC, I did update the pin in the 5290 PR.

It is pinned at https://github.com/tmalsburg/helm-bibtex/commit/a0d32ab16748b7b0c43d6421f1b497b7caf8e590

The last commit before the local-bib support for `org-cite`

**Comment by bdarcus** [comment]
I'll fix it when I update the bibtex-actions pin.

**Comment by aikrahguzar** [comment]
> But the result is as if the `bibtex-actions-open-link` command is not receiving the key as a list, which is what it's expecting.

`bibtex-actions-citation-key-at-point` returns a string which encodes the list of keys by separating with `&`. Where do we parse this string into a list again before passing it to the `bibtex-actions-open-link`? If you generalized `bibtex-actions-open-link` from accepting a single key to a list of keys or else changed it from function on strings to a function on list of strings  that would explain the problem.

**Comment by bdarcus** [comment]
> Where do we parse this string into a list again before passing it to the `bibtex-actions-open-link`? 

I think embark does some magic there, and somehow knows how to handle it based on the `crm-separator` value.

> If you generalized `bibtex-actions-open-link` from accepting a single key to a list of keys or else changed it from function on strings to a function on list of strings that would explain the problem.

Neither of which is the case. Right?

**Comment by aikrahguzar** [comment]
> > Where do we parse this string into a list again before passing it to the `bibtex-actions-open-link`?
> 
> I think embark does some magic there, and somehow knows how to handle it based on the `crm-separator` value.

It makes sense if embark dose the parsing. 

The `crm-separator` for me by default is `"[ 	]*,[ 	]*"`. It is let-bound to be `(crm-separator "\\s-*&\\s-*")` in `bibtex-actions-select-keys` but that is not relevant for `bibtex-actions-open-link`. I don't understand regex at all but if we need to rely `crm-separator` for embark we need to let bind it in `ba-open-link` to something that works for `&`.  Though I don't see why that would make a difference between the two branches.

> > If you generalized `bibtex-actions-open-link` from accepting a single key to a list of keys or else changed it from function on strings to a function on list of strings that would explain the problem.
> 
> Neither of which is the case. Right?

**Comment by oantolin** [comment]
I could quite follow this for lack of domain knowledge about this package, and so I currently have no clue what is casuing this issue, but I think I can at least clear up the crm question. The way embark passes a target to a command that you use as an action is as follows: it run the command interactively just as the user had run it, and then the first time the command prompts the user for some text in the minibuffer, embark simulates typing the target at the minibuffer prompt and pressing `RET`.

So, what happens here is that commands like `bibtex-actions-open-link` can be called in two different ways: from Emacs Lisp code or interactively, say by using `M-x`. That command when called from Emacs Lisp takes and argument which is a list of citation keys, but if called interactively it first calls `bibtex-actions-select-keys` to prompt the user for a list of keys. That function uses `completing-read-multiple` with `crm-separator` set to `"\\s-*&\\s-*"`. Then the list of keys returned by `bibtex-actions-select-keys` is what `bibtex-actions-open-link` uses as the argument.

This means that if you call `bibtex-actions-open-link` as an Embark action with a string of `&` separated citation keys, things should work: Embark will call `bibtex-actions-open-link` _interactively_, which means that `bibtex-actions-open-link` will use `bibtex-actions-select-keys` to prompt the using using crm, at that prompt Embark will insert the `&`-separated target and press `RET` for you, `bibtex-actions-select-keys` will return a list of keys and that gets used as the argument to `bibtex-actions-open-link`.

In particular, the answer to @aikrahguzar's question "Where do we parse this string into a list again before passing it to the bibtex-actions-open-link?" is that it happens in `bibtex-actions-select-keys` which is called by the `interactive` declaration in `bibtex-actions-open-link`.

Does that make sense?

**Comment by bdarcus** [comment]
I think where I keep getting tripped up is the in-buffer at-point angle, which is what is at issue here.

Embark-act works fine in the minibuffer, and was working fine in the buffer, but something on the latter broke in the past few days, and we're having trouble figuring it out.

**Comment by oantolin** [comment]
Is there a way to test the thing that's problematic if I'm still on Org 9.4.6?

**Comment by bdarcus** [comment]
No, it's a 9.5 feature on the master branch only ATM.

**Comment by aikrahguzar** [comment]
> Does that make sense?

Thank you, I am still a emacs newbie so that is very helpful and cleared up the picture for me. I didn't even realize that `bibtex-actions-select-keys` was involved in any way!

Now I am really confused about what is happening, the sequence of events as I understand it is:

1) Embark gets a string, this string is what we expect.
2) It feeds it interactively to a function. This passes it though `completing-read-mulitple` which always returns a list of strings.

So `bibtex-actions-open-link` should always get a list of strings. @bdarcus  is the problem that the list is empty? 

I will unpin `bibtex-completion` later today so I can reproduce it fully.

**Comment by bdarcus** [comment]
> @bdarcus is the problem that the list is empty?

Yes. You can see what the commands are getting by the "not found" messages, which print the keys. They are now always nil.
