### ISSUE TITLE
Add file fields to candidates

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#236]
I think we need to add back "file" fields (and "url"?) to candidates, which would include:

1. Adding a mapping for that.
2. Including it even if the templates don't.

cc @aikrahguzar

**Comment by aikrahguzar** [comment]
There is
```elisp
(fields-for-symbols (list "doi" "url" bibtex-actions-file-variable))
```
in `bibtex-actions--fields-to-parse`. "url" and "file" (through the variable) are already there.
More fields can be added there if needed.
