### ISSUE TITLE
Narrowing input in bibtex-actions-open-entry skips relevant results

### ISSUE THREAD

**Issue by myshevchuk** [bdarcus/bibtex-actions#252]
Hi! I've been happily using Bibtex-actions for about a month now after Doom has finally switched to Vertico/Embark. Today however I've discovered an unexpected behaviour as described below.

**Describe the bug**
When typing the input string, narrowing seems to consider the text that is visible in the completion candidates list, rather than the BibTeX entry data.

**To Reproduce**
1. Use the default value of `bibtex-actions-template`, e.g. 20 characters for author
2. Choose a BibTeX entry with several authors so that their combined name length is >20 and last author's name would not be shown in the completion list 
3. Call `bibtex-actions-open-entry` and start typing the last author's name
4. The BibTeX entry does not appear in the search results

**Expected behavior**
The BibTeX entry appears in the search results

**Screenshots**
Searching by an author whose name does not fit into the candidate line, the entry does not appear in the search:

![Screen Shot 2021-08-23 at 23 34 51](https://user-images.githubusercontent.com/24212814/130522695-30b01e05-fabf-4f0c-a9e8-31e0f2d327f5.png)

Searching by the same author after adjusting `bibtex-actions-template` so that their name fits into the candidate line. The entry correctly appears in the search:

![Screen Shot 2021-08-23 at 23 32 51](https://user-images.githubusercontent.com/24212814/130522390-77737632-6720-4f08-9350-1c271577aadf.png)

Searching by the same author using Ivy-bibtex, the name does not fit into the candidate line, but the entry nevertheless correctly appears in the search:

![Screen Shot 2021-08-23 at 23 31 04](https://user-images.githubusercontent.com/24212814/130522210-33d4a6b6-ad8f-4361-8714-75fee75382fb.png)

**Emacs version:**
Emacs 27.2

**Comment by bdarcus** [comment]
This may be an (unintended) consequence of recent changes, including #222, but we can certainly fix it; just a question of how best to do that.

Are you sure that behavior wasn't happening earlier though? I don't think anything changed that would impact this.

So let me clarify a bit:

Completing-read works different than ivy (and helm).

The latter has display-tranformers, so the candidates you search on can be different than the displayed candidates, but you still get match highlighting. That's what ivy-bibtex uses for this.

That's not currently possible in completing-read (though may change in the future). If you use "display" to show something different, you lose match-highlighting. Indeed, early version did that, but I got some complaints.

So options:

1. given the importance of authors names, we could maybe put the full author names as the actual candidate sub-strings there, but use a "display" property to display only the shortened version
2. we could stick the full author names in the "invisible" portion of the candidate strings, which currently includes metadata like `has:pdf` such that it can be searched on
3. increase the default field width and include a note in the README about how this works (the simplest and most general)

Thoughts?

cc @aikrahguzar

**Comment by aikrahguzar** [comment]
> This may be an (unintended) consequence of recent changes, including #222, but we can certainly fix it; just a question of how best to do that.
> 
> But, are you sure that behavior wasn't happening earlier though? I don't think anything changed that would impact this (except "additional-search-fields" no longer works).

I don't see how this was not the case before since the beginning. String truncation has always been there so #222 seems irrelevant to me unless I am missing something.

This aspect is certainly worth improving. 

> 
> In any case, let me clarify a bit:
> 
> Completing-read works different than ivy (and helm).
> 
> The latter has display-tranformers, so the candidates you search on can be different than the displayed candidates, but you still get match highlighting. That's what ivy-bibtex uses for this.
> 
> That's not currently possible in completing-read (though may change in the future). If you use "display" to show something different, you lose match-highlighting. Indeed, early versions did that, but I got some complaints. Upshot is (notwithstanding the invisible section I note below) if you don't see it, you can't search on it.
> 
> So options:
> 
>     1. given the importance of authors names, we could maybe put the full author names as the actual candidate sub-strings there, but use a "display" property to display only the shortened version; except, we lose match-highlighting for that content
> 
>     2. we could stick the full author names in an "invisible" portion of the candidate strings
> 
>     3. increase the default field width and include a note in the README about how this works (the cleanest, simplest and most general solution, I think)

1 seems doable but I think it will mess up the highlighting of search results. 

I think a relatively simple solution would be to not do string truncation as we do now but instead if a field value overflows the width in the template we make the overflowing part of the string invisible. This way we don't need to treat any field specially. Any field in the template is searchable (up to other display  transformations like shortening author names, it would be difficult to have all three of shortening, being able to search full name and alignment of columns.)

**Comment by aikrahguzar** [comment]
Added a commit to https://github.com/bdarcus/bibtex-actions/pull/250 which does what I suggested above. After it, this seems fixed,

![2021-08-24T11:47:19,252028352+02:00](https://user-images.githubusercontent.com/88336724/130596283-819b783b-55f4-4a3c-9f87-c8fce15791cc.png)

All three results are visible because there is a hidden author named `Doa`. The string for the first result is,

```elisp
#("de Villiers, Smith, Doa, Jennifer Jones     2015     An example title                                           test1              book                                                            has:files  has:link is:local test1" 0 10
    (face bibtex-actions-highlight)
    10 39
    (face bibtex-actions-highlight invisible t)
    39 101
    (face bibtex-actions-highlight)
    102 193
    (face bibtex-actions)
    194 229
    (invisible t))
```

**Comment by bdarcus** [comment]
> I think a relatively simple solution would be to not do string truncation as we do now but instead if a field value overflows the width in the template we make the overflowing part of the string invisible.

Perfect!

**Comment by bdarcus** [comment]
BTW, I noticed you have the same display bug with the "files" symbol. I guess that's an Emacs bug?

**Comment by aikrahguzar** [comment]
> BTW, I noticed you have the same display bug with the "files" symbol. I guess that's an Emacs bug?

I think the symbol is due to whatever font emacs is falling back to for that character. An appropriate `set-fontset-font` should fix this.

**Comment by bdarcus** [comment]
> I think the symbol is due to whatever font emacs is falling back to for that character. An appropriate `set-fontset-font` should fix this.

I don't think anything has changed on that in my config though; I just use jetbrains.

Anyway, I merged #250, so this should be fixed. Let us know @myshevchuk.

**Comment by aikrahguzar** [comment]
> I don't think anything has changed on that in my config though; I just use jetbrains.

My main font doesn't have this symbol so it is rendered using a fallback one. You can use `SPC h ' (describe-char)` with point on the symbol to see which font emacs is using for it.

**Comment by bdarcus** [comment]
Hmm ... jetbrains does have that glyph, it appears, but this is what it says:

```console
    ftcrhb:-unknown-file-icons-normal-normal-normal-*-12-*-*-*-*-0-iso10646-1 (#x30)
```

BTW, I started noting this maybe six weeks ago.

**Comment by myshevchuk** [comment]
Great! Works as expected, thanks a lot!
