### ISSUE TITLE
Continued alignment issues

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#253]
Sorry @aikrahguzar, but:

![image](https://user-images.githubusercontent.com/1134/130629182-2309ccb8-9a59-4015-bce2-c662485df3b4.png)

If you confirm the same thing (here I changed to just using letters for the symbols), it occurs to me maybe a better option is to put the current prefix as a suffix, and so changed from affixation to annotation?

Or, alternately, don't use spaces at all here, per earlier suggestion.

**Comment by aikrahguzar** [comment]
> Sorry @aikrahguzar, but:
> 
> ![image](https://user-images.githubusercontent.com/1134/130629182-2309ccb8-9a59-4015-bce2-c662485df3b4.png)
> 
> If you confirm the same thing (here I changed to just using letters for the symbols), it occurs to me maybe a better option is to put the current prefix as a suffix, and so changed from affixation to annotation?
> 

Link character has has string-width too so its absence is indicated with two spaces. I think you probably didn't change it to a single space.

**Comment by bdarcus** [comment]
Yep!
