### ISSUE TITLE
Add a note template

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#269]
The current default note function is simple, with no ability for a user to change the output, other than to use a different function.

It would be nice to have at least the title field be configurable with a template.

I see two options:

1. just have a template for this exactly the same as for the library display, and use `format-entry` on it
2. use `org-capture` somehow

1 seems simpler/more general, and would just be something like:

```elisp
(setq bibtex-actions-note-title-template 
  "Notes on {author editor:15}, {title:40}")
```

**Comment by bdarcus** [comment]
@aikrahguzar - shouldn't this work?

```elisp
(defvar my/temp "Notes on ${author editor:15}, ${title:40}")

(bibtex-actions--format-entry
        (bibtex-actions-get-entry "low2001")
        250
        my/temp)
```

And if I go this way, how should that relate to `bibtex-actions-template`? Maybe it shouldn't be a cons?

Finally, while I think about, should I change the function name to `bibtex-actions-format-entry`?

**Comment by aikrahguzar** [comment]
I am not sure where the notes template is going to be used. From the example it seems like a completely different display from `bibtex-actions-select-keys`, is that right? If that is the case I think we have two disjoint situations,
1) We can have a template with explicit widths with a column view
2) No explicit widths in any field so the view is that of a single string

i.e we don't have to deal with a situation where some fields have a width but others don't. In this case it seems simpler to just define another formatting function for the second case. I think the following will work, (really bad name but it is just for illustration)
```elisp
(defun bibtex-actions--format-entry-no-widths (entry format-string)
  "Formats a BibTeX ENTRY for display in results list. and the display format is governed by
FORMAT-STRING."
  (s-format
   format-string
   (lambda (raw-field)
     (let ((field-names (split-string (car field) "[ ]+")))
       (bibtex-actions-display-value field-names entry)))))
``` 
And then we can add the formatting function as an additional (possibly optional) argument to the `bibtex-actions--format-candidates` and `bibtex-actions--format-entry` and pass different functions depending on the command called, and in that case it does make sense to make them public.

**Comment by bdarcus** [comment]
> I am not sure where the notes template is going to be used. From the example it seems like a completely different display from `bibtex-actions-select-keys`, is that right?

Yes. It's for inserting content in a new file.

But I can imagine it being useful for other, non-select-keys, use cases.

**Comment by bdarcus** [comment]
Mostly implemented on linked PR, with following default note template string:

```elisp
 "#+title: Notes on ${author editor}, ${title}")
```
