### ISSUE TITLE
PDF file always open externally, even with pdf-tools installed.

### ISSUE THREAD

**Issue by pRot0ta1p** [bdarcus/bibtex-actions#282]
**To Reproduce**
`M-x bibtex-actions-open` and select an entry, hit enter, select a PDF file from the given options,
the PDF file is opened with browser somehow ... even tho I've pdf-tools installed.

Same thing happens if I call `embark-act` after `bibtex-actions-open` and select open library files.

Meanwhile `M-x bibtex-actions-open-library-files` will always open PDF files with pdf-tools.

**Expected behavior**
 Maybe I missed some settings, but I think bibtex-actions should use pdf-tools when possible.

my config:
```emacs-lisp
(straight-use-package 'bibtex-actions)

(with-eval-after-load 'bibtex-actions
  (setq bibtex-actions-open-library-file-external nil
		bibtex-actions-bibliography '("/path/to/bib")
		bibtex-actions-library-paths '("/path/to/lib")
		bibtex-actions-notes-paths '("/path/to/notes")
		bibtex-actions-file-variable "File"
		bibtex-actions-file-open-note-function #'orb-edit-note
		bibtex-actions-default-action #'bibtex-actions-open-library-files)
  (with-eval-after-load 'embark
	(add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
	(add-to-list 'embark-keymap-alist '(bib-reference . bibtex-actions-map))
	(add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))))
```

**Comment by bdarcus** [comment]
What happens if you set `bibtex-actions-open-library-file-external` to nil?

**Comment by pRot0ta1p** [comment]
> What happens if you do `(setq bibtex-actions-open-library-file-external nil)`?
>
Already tried that, `(setq bibtex-actions-open-library-file-external nil)` will only change the behaviour of  
`bibtex-actions-open-library-files`, I have to advice a override of function `bibtex-actions-file-open-external` to foce it
open internally.

So I took a look at the source code  and  found that `bibtex-actions-open` is hard coded to open pdf externally:
https://github.com/bdarcus/bibtex-actions/blob/75a7ffa18de0da5f6a90cf47bbd63f019a887218/bibtex-actions.el#L624-L628
maybe `(file-name-extension resource)` should be checked against `auto-mode-alist`, or make a new customizable to
let user to decide what file extension should be opened internally?

**Comment by bdarcus** [comment]
The hard-coding is an oversight, so obviously will address.

Let me put it differently: if you use find-file with a PDF, will it open in pdf-tools?

I do want to make sure whatever solution is not assuming PDFs though.

**Comment by pRot0ta1p** [comment]
Yes, find-file will open a PDF file with pdf-tools, and if pdf-tools is not installed Emacs will use doc-view.

**Comment by bdarcus** [comment]
Ok, I'll modify the behavior of open to match open-library-file, and maybe set external to nil by default.

**Comment by salutis** [comment]
> Ok, I'll modify the behavior of open to match open-library-file, and maybe set external to nil by default.

Thank you. I also have the same problem as @pRot0ta1p.

**Comment by bdarcus** [comment]
I am working on wrapping up a more critical issue, but when I get to this (soon) I may ask for feedback from you two on some details.

**Comment by pRot0ta1p** [comment]
> I am working on wrapping up a more critical issue, but when I get to this (soon) I may ask for feedback from you two on some details.

Take your time: , I understand that bibtex-actions is going through some major changes, this issue is not a big problem.

Mean while if somebody want get over this problem, this piece of code might help:
```emacs-lisp
(defun my/bibtex-action-open (file)
  (find-file file))
(add-function :override 'bibtex-actions-file-open-external 'my/bibtex-action-open)
;;override  bibtex-actions-file-open-external to find-file
```

**Comment by salutis** [comment]
bdarcus ***@***.***> writes:

> Closed #282 via #295. 

This works superbly now. I can open all my links, images, books, papers, and everything. Thank you!

**Comment by bdarcus** [comment]
> This works superbly now. I can open all my links, images, books, papers, and everything.

WDYT about removing `bibtex-actions-open`?

Are you using that, or more `bibtex-actions-open-library-files`?

**Comment by salutis** [comment]
@bdarcus I use `bibtex-actions-open` and then something else to insert a key. Nothing else. The only aspect of it that I `bibtex-actions-open` dislike is the large number of `RET` `RET` ... I have to type to confirm all those multi-selections that I never use. I would love to set some variable to disable all that.

**Comment by bdarcus** [comment]
`bibtex-actions-open-library-files` has an optional (it's off by default ATM) file prompt like the more general open command, but with the advantage that the candidates are typed as files, so that display and functionality can be enhanced with marginalia, consult, and embark.

You might play with that a bit and see WYT.

I can't really to reproduce that functionality using both links and files (different types). I could use `consult--multi`, but that would only allow one to open a single selection at a time.

Why I was contemplating removing open; could allow more focused `open-link` and `open-library-files` commands.

But I'm torn.
