### ISSUE TITLE
Source files only opening for some bibtex entries.

### ISSUE THREAD

**Issue by anaxonda** [bdarcus/bibtex-actions#283]
**Describe the bug**
When running either `bibtex-actions-open` or `bibtex-actions-open-library-files`, the source files only open for some entries.  For bibtex entry types described below I get the error `No file(s) found for ("name of key")`, or a "Related resources" minibuffer  that has no entries.
**Expected behavior**
Either source file should open, or selected library file should open based off of the bibtex `file` field. Opening files works fine in helm-bibtex, so I guess its not a bibtex-completion issue.

**Emacs version:**
28.0.5
**Additional context**
I have two bibliography files, one generated by Zotero and one by Calibre. 

Zotero bibtex entries with multiple files listed in the `file` field do not open. Entries with single files listed work fine. Here is an example of a bibtex entry with multiple files listed that does not work:
```
@article{kaneReconsideringFireEcology2020,
  title = {Reconsidering the Fire Ecology of the Iconic {{American}} Chestnut},
  author = {Kane, Jeffrey M. and Varner, J. Morgan and Stambaugh, Michael C. and Saunders, Michael R.},
  date = {2020},
  journaltitle = {Ecosphere},
  volume = {11},
  number = {10},
  pages = {e03267},
  issn = {2150-8925},
  doi = {10.1002/ecs2.3267},
  url = {https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecs2.3267},
  urldate = {2021-02-20},
  langid = {english},
  keywords = {American chestnut,Castanea dentata,fire ecology,fire history,fire-adaptive traits,foundation species,restoration},
  annotation = {\_eprint: https://esajournals.onlinelibrary.wiley.com/doi/pdf/10.1002/ecs2.3267},
  file = {../../Zotero/storage/IXT6SZDI/Kane et al. - 2020 - Reconsidering the fire ecology of the iconic Ameri.pdf;../../Zotero/storage/M4T63FTP/ecs2.html}
```
The other case is bibtex entries generated by calibre (of which none work):
```
@book{ ThompsonDArcyWentworth567,
    author_sort = "Wentworth, Thompson D'Arcy",
    author = "Thompson D'Arcy Wentworth",
    cover = "/home/Documents/Library/Thompson D'Arcy Wentworth/On Growth and Form (567)/cover.jpg",
    formats = "pdf",
    file = ":/home/Documents/Library/Thompson D'Arcy Wentworth/On Growth and Form (567)/On Growth and Form - Thompson D'Arcy Wentworth.pdf:PDF",
    calibreid = "567",
    identifiers = "google:XGaIzQEACAAJ,isbn:9780243783687",
    isbn = "978-02-4378-368-7",
    languages = "eng",
    library_name = "Library",
    year = "1901",
    month = "Dec",
    publisher = "Forgotten Books.",
    volume = "1",
    size = "100095835 octets",
    timestamp = "2020-12-16",
    title = "On Growth and Form",
    title_sort = "On Growth and Form",
    uuid = "8f6fe880-f34d-4e04-8cb2-9c6bc5c50f65" }
```

**Comment by bdarcus** [comment]
@thisirs - here's an example of why there might be value in allow multiple parsing functions.

This user has bib files with entries created in two different programs, with slightly different syntaxes on the file field.

@anaxonda - it's not really a bug; more a feature request to support calibre style file fields.

**Comment by anaxonda** [comment]
@bdarcus  You can have multiple files per entry. Not sure about the colon being the separator, I believe the paths are separated by `,`.

Here is the calibre python script that generates the bibtex catalog:
https://github.com/kovidgoyal/calibre/blob/master/src/calibre/library/catalogs/bibtex.py

**Comment by bdarcus** [comment]
I think what we want is to change `bibtex-actions-file-parser-function` to `bibtex-actions-file-parser-functions` (plural), add a calibre one (or add it to the wiki; am not sure), so then you can do:

```elisp
(setq bibtex-actions-file-parser-functions
  '(bibtex-actions-file-parser-zotero 
    bibtex-actions-file-parser-calibre))
```

**Comment by bdarcus** [comment]
@anaxonda - I just merged the PR from @thisirs.

Give it a try?

**Comment by anaxonda** [comment]
Sorry, my doom config has gone all wonky, and I haven't been able to test it yet.

**Comment by anaxonda** [comment]
Working well for me.
