### ISSUE TITLE
bibtex-actions-open-notes returns error

### ISSUE THREAD

**Issue by mbosley** [bdarcus/bibtex-actions#292]
**Describe the bug**
[From the doom emacs PR](https://github.com/hlissner/doom-emacs/pull/5290). After setting up the biblio module according to the readme, including specifying my library, bib, and notes locations, `org-cite-insert` works correctly, and does accessing PDFs through `embark-act`. However, I cannot access notes through `embark-act` or by using `bibtex-actions-open-notes`. Instead, I get `find-file-noselect: Wrong type argument: stringp, nil`.

**Emacs version:**
28.0.50

**Comment by bdarcus** [comment]
Thanks.

I see the problem.

**Comment by bdarcus** [comment]
Should be fixed. Let me know.

**Comment by mbosley** [comment]
Running `embark-act` then hitting `n` for notes now opens the PDF associated with the citation, rather than the notes. This might be related to the fact that I'm getting the standard embark output in the mini buffer (see screenshot) rather than the org-cite customized mini buffer. As before, I have the packages set up exactly as in the doom PR.

![Screen Shot 2021-09-17 at 10 15 23 AM](https://user-images.githubusercontent.com/37943910/133797564-bcdc5321-3aca-48f4-a0ee-e3464306438f.png)
.

**Comment by bdarcus** [comment]
Yeah, I subsequently noticed a problem with embark and the change.

I'll take a look later. Sorry about this.

**Comment by bdarcus** [comment]
I'm fixing it on this branch. Just needs more testing.

#294

**Comment by mbosley** [comment]
I updated to #294, and `bibtex-actions-open-notes` is giving me `find-file-noselect: Wrong type argument: stringp, nil` again.

**Comment by bdarcus** [comment]
I'm working more on these functions on #295.

But I have not seen any problems with open-notes.

Can you post more details, including ideally a stack trace?

**Comment by mbosley** [comment]
I figured it out: setting `bibtex-actions-notes-paths` to the proper directory works, but `bibtex-actions-notes-path` does not.
