### ISSUE TITLE
Support parsing bibtex-completion's file entry style.

### ISSUE THREAD

**Issue by pRot0ta1p** [bdarcus/bibtex-actions#296]
bibtex-completion uses syntax like this for multi-file file entries in bib file.

```
File = {:/path/to/article.pdf:PDF;:/path/to/supplementary_materials.pdf:PDF}
```

which is  not support by `bibtex-actions-file-parser-zotero` or `bibtex-actions-file-parser-calibre` currently,
I just migrated from ivy-bibtex-completion so I have a lot of the old style file entries in my bib file, and don't really want to bother changing the file entry style ('cause I suck at regex :joy: ). So I wrote a parser function to parse bibtex-completion's style file entries.

```emacs-lisp
  (defun bibtex-actions-file-parser-bibtex-complition (dirs file-field)
	(let ((parts (split-string file-field ";" 'omit-nulls)))
	  (seq-mapcat
	   (lambda (part)
		 (let ((fn (car (split-string part ":PDF" t ":"))))
		   (mapcar (apply-partially #'expand-file-name fn) dirs)))
	   parts)))
```

It works for me, not sure if its robust enough tho...

**Comment by bdarcus** [comment]
Do you know what the source of that syntax is?

It's not bibtex-completion. Maybe Mendeley?

**Comment by bdarcus** [comment]
Yes. I'm just trying to figure out how best to do that, given how similar they are.

**Comment by pRot0ta1p** [comment]
Zotero and Mendeley use semi-colon for delimiter, but Mendeley also enclose the file path with `: ... :pdf`.

I don't think its necessary to merge all of the function into one, but I think `bibtex-actions-file-parser-zotero`, and `bibtex-actions-file-parser-calibre` can replace the default paser `bibtex-actions-file-parser-default`, since they can handles single-file file entries.

Even bibtex-completion use cl-loop for conditional parsing (in `bibtex-completion-find-pdf-in-field`), I would tend to keeping this one to one parsing function to syntax logic , could be potencially more flexable.

**Comment by bdarcus** [comment]
> It works for me, not sure if its robust enough tho...

PS - the only problem I see with your example is the ` ":PDF"`. Notwithstanding the case issue, it means it would only work for pdfs.

Why we split on the colon.

**Comment by bdarcus** [comment]
Aside from testing the branch, it would help to post examples that fail.

**Comment by bdarcus** [comment]
> we should use regex like `":\\(.*\\):.*;"` indead of `split-string` maybe ?

Also, why "instead of"? Split-string takes a regex.

**Comment by pRot0ta1p** [comment]
Entries like `File = {:~/test/file1.pdf:pdf;:~/test/file2.pdf:pdf}` are ok, 
but `File = {:e:/home/test/file1.pdf:pdf;:e:/home/test/file2.pdf:pdf}` or 
`File = {:e\:/home/test/file1.pdf:pdf;:e\:/home/test/file2.pdf:pdf}` (Mendely sometimes do this , tring to escape the fist colon in path?) are not recognized .

Since `:` can be a part of file path so `split-string` is not suitable ? I'm thinking of something like:
```emacs-lisp
(defun bibtex-actions-file-parser-triplet (dirs file-field)
  "Return a list of files from DIRS and a FILE-FIELD formatted as a triplet.

Example: ':/path/to/test.pdf:PDF'."
  (let ((parts (split-string file-field "[,;]" 'omit-nulls)))
    (seq-mapcat
     (lambda (part)
	   (when (string-match ":\\(.*\\):.*" part)
		 (let ((fn (replace-regexp-in-string "\\:" ":" (match-string 1 part))))
           (mapcar (apply-partially #'expand-file-name fn) dirs))))
     parts)))
```
It works for `File = {:e:/home/test/file1.pdf:pdf;:e:/home/test/file2.pdf:pdf}` 
but not for `File = {:e\:/home/test/file1.pdf:pdf;:e\:/home/test/file2.pdf:pdf}`,  I don't know why, the `replace-regex-in-string` should un-escape the escapted colon...

**Comment by allumik** [comment]
I guess this the right issue to follow up on...

I use Zotero with ZotFile on Windows to manage PDF's in custom directory. When trying to open a pdf from citar with `citar-open-files`, it is unable to do so, giving me the following (edited a bit) error:

```
None of the files for ‘paperOfInterest2022’ exist; check ‘citar-library-paths’ and ‘citar-file-parser-functions’: ("C\\:\\\\Users\\\\username\\\\Documents\\\\Biblio\\\\Articles\\\\2022\\\\Author_et_al-Paper_of_interest.pdf")
```

While I'm not that familiar with Windows pathnames, I figured out messing on pwsh that drive letter "C\\: ..." is not valid.

In the BIB file (generated with Zotero's BetterBibtex plugin) the field is:

```
@article{articleOfInterest2022,
    ...
    file = {C\:\\Users\\username\\Documents\\Biblio\\Articles\\2022\\articleOfInterst2022.pdf}
}
```
