### ISSUE TITLE
bibtex-actions-open-notes error

### ISSUE THREAD

**Issue by anaxonda** [bdarcus/bibtex-actions#299]
Running bibtex-actions-open-notes gives error: `Wrong number of arguments: (1 . 1), 2 [2 times]`.

Running `trace-function` gives: 
`1 -> (bibtex-actions-open-notes ((#1="kaneReconsideringFireEcology2020" ("file" . "../../Zotero/storage/IXT6SZDI/Kane et al. - 2020 - Reconsidering the fire ecology of the iconic Ameri.pdf;../../Zotero/storage/M4T63FTP/ecs2.html") ("keywords" . "American chestnut,Castanea dentata,fire ecology,fire history,fire-adaptive traits,foundation species,restoration") ("url" . "https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecs2.3267") ("doi" . "10.1002/ecs2.3267") ("date" . "2020") ("author" . "Kane, Jeffrey M. and Varner, J. Morgan and Stambaugh, Michael C. and Saunders, Michael R.") ("title" . "Reconsidering the Fire Ecology of the Iconic {{American}} Chestnut") ("=type=" . "article") ("=key=" . #1#))))
1 <- bibtex-actions-open-notes: !non-local\ exit!`

**Comment by bdarcus** [comment]
I've not seen this.

1. What commit version?
2. In what context? With `embark-act`, or from `M-x`?

**Comment by bdarcus** [comment]
What note function?

**Comment by anaxonda** [comment]
`bibtex-actions-open-notes`

**Comment by bdarcus** [comment]
Sorry; I mean what is the value of `bibtex-actions-file-open-note-function`?

I assume from your answer it's the default; that you're not using another function, like from org-roam-bibtex?

**Comment by anaxonda** [comment]
Alright, I feel fairly stupid. 

I was using `org-roam-bibtex` as `bibtex-actions-file-open-note-function`. It turns out `org-roam-bibtex-mode` was not being enabled, and that was triggering the error. 

So all good on this end now, and thanks as usual.

**Comment by bdarcus** [comment]
You might give the default notes function a try at some point.

**Comment by anaxonda** [comment]
I will give it a look.
