### ISSUE TITLE
Multiple selections not fully inserted when point is inside cite links

### ISSUE THREAD

**Issue by liebkne** [bdarcus/bibtex-actions#300]
**Describe the bug**
Multiple selections not fully inserted when point is inside cite links. 

However, everything works well when point is not in cite links.

**To Reproduce**
1. Place point inside some cite link like `[cite:@ahuja-2020-acc-nlu-tod]`.
2. Use `org-cite-insert` to select multiple bib entries.
3. Press enter to insert selected entries.
4. Only one entry is inserted.

**Expected behavior**
All entries should be inserted.

**Emacs version:**
`GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3) of 2021-04-02`

**bibtex-actions**
`master`

**Configs**
```el

(use-package bibtex-actions
 :demand t
 :after org
 :init
 (setq bibtex-actions-templates
       '((main . "${date year issued:4}  ${title:80}  ${author editor:30}")
         (suffix . "${=key= id:20}")
         (note . "#+title: ${title}\n#+roam_refs: cite:${=key=}\n\n\n\n#+print_bibliography:"))
       bibtex-actions-at-point-function 'bibtex-actions-dwim
       bibtex-actions-symbols
       '((file . ("F" . " "))
         (note . ("N" . " "))
         (Link . ("L" . " "))))

 (use-package citeproc
   :demand t
   :after org)

 (use-package oc-bibtex-actions
   :straight bibtex-actions
   :demand t
   :after (:all oc bibtex-actions)
   :init (setq org-cite-insert-processor 'oc-bibtex-actions
               org-cite-follow-processor 'oc-bibtex-actions
               org-cite-activate-processor 'basic))

 :config
 (bibtex-actions-filenotify-setup '(LaTeX-mode-hook org-mode-hook))

 (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
 (add-to-list 'embark-keymap-alist '(bib-reference . bibtex-actions-map))
 (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))

 (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple))
```

**Comment by bdarcus** [comment]
You mean when point is on a citation-reference; the key?

That behavior is not controlled by this code, but by org-cite.

It's not really a bug; the idea is you're editing a single key.

I actually agree it's probably not ideal.

**Comment by bdarcus** [comment]
I reported this to the org list to see if we can get it changed.

**Comment by bdarcus** [comment]
BTW, I'm also considering porting some of the org-ref-cite commands for citation editing, if you have any thoughts on that.

**Comment by liebkne** [comment]
Thanks for the clarification.

> I'm also considering porting some of the org-ref-cite commands for citation editing

I personally found the [editing commands](https://github.com/jkitchin/org-ref-cite#editing-the-citation-at-point) are quite handy.

**Comment by bdarcus** [comment]
I started to play with it on #303.

Are some more useful than others?

**Comment by bdarcus** [comment]
PS - if you have feedback on this, please post to #302 or #303.
