### ISSUE TITLE
Note template is not empty when using `oc-bibtex-actions`

### ISSUE THREAD

**Issue by dschrempf** [bdarcus/bibtex-actions#311]
**Describe the bug**
I want to have an empty note template. I am not able to achieve this using `oc-bibtex-actions`.

**To Reproduce**
- load `oc-bibtex-actions`
- set `(add-to-list 'bibtex-actions-templates '(note . ""))`
- create a new note, the file contents are not empty but
```
:PROPERTIES:
:ID:  9c59f72b-d376-4862-97ca-f348752ead25
:END:

```
(there is also a newline after the property drawer).

**Expected behavior**
The note is empty.

**Comment by bdarcus** [comment]
To be clear, this is for use in org?

**Comment by dschrempf** [comment]
Yes, sorry I should have specified this. The note file is an Org file.

On another topic: Is it possible to format the date in the template? This was/is possible using `bibtex-completion-notes-template-multiple-files` and, e.g., `date: %<%B %e, %Y>`.

Thanks for your help!

**Comment by bdarcus** [comment]
> On another topic: Is it possible to format the date in the template? This was/is possible using bibtex-completion-notes-template-multiple-files and, e.g., date: %<%B %e, %Y>.

The current templating functions aren't really designed for that fine-grained formatting; you can just get the year, for example, by doing `${issued:4}`.

@aikrahguzar - WDYT: is it practical to extend to do this?

I will say, by way of context, that the primary goal in replacing the bibtex-completion notes code, aside from ultimately removing a dependency, was to make it easy to swap in different functions; including, for example, one from org-roam-bibtex.

**Comment by bdarcus** [comment]
To go back to your OP, I'm not sure how best to handle this.

I use org-roam, so personally need the ID at the top ;-)

I suppose I could:

1. create a separate "plain" function without it, and/or rename this one
2. somehow create a template variable to add the org-id, so it could be added to the template
3. have a defcustom to add the org-id

3 seems the worst option. Not sure about the first 2.

**Comment by dschrempf** [comment]
I understand! In my opinion, it should be possible to have an empty template. Maybe it would be easiest to give the user power to provide a custom template inserting function? The default one could be `bibtex-actions-file-open-notes-default-org`. (Well, we would need to split out the "open file" stuff, and the "insert template" stuff.

**Comment by bdarcus** [comment]
> Maybe it would be easiest to give the user power to provide a custom template inserting function?

That's already possible. You can just create your own function and use that for `bibtex-actions-file-open-notes-function`; something like:

```elisp
(defun bibtex-actions-file-open-notes-plain-org (key entry)
  "Open a note file from KEY and ENTRY."
  (if-let* ((file
             (caar (bibtex-actions-file--get-note-filename
                    key
                    bibtex-actions-notes-paths '("org"))))
            (file-exists (file-exists-p file)))
      (funcall bibtex-actions-file-open-function file)
    (let ((note-meta
            (bibtex-actions--format-entry-no-widths
             entry
             (bibtex-actions-get-template 'note))))
      (funcall bibtex-actions-file-open-function file)
      ;; This just overrides other template insertion.
      (erase-buffer)
      (insert note-meta))))
```

**Comment by dschrempf** [comment]
OK, this worked, but it is a little complicated for having an empty template :-). Thanks for your help! Feel free to close this issue!

**Comment by bdarcus** [comment]
No, it's a far point. I'll see if I can implement a straightforward solution.

I was just saying there are workarounds now.
