### ISSUE TITLE
how to create a org note for a selected entry?

### ISSUE THREAD

**Issue by RNAer** [bdarcus/bibtex-actions#317]
When I looked into the doc and skimmed the code a bit, there is no way to create a org file for a given bibtex entry? If I understand correctly, even though the `bibtex-actions-templates` can define a note template below, I can only create a note using org-roam-bibtex using `(setq bibtex-actions-file-open-note-function 'orb-bibtex-actions-edit-note)`?

```
((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
 (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords keywords:*}")
 (note . "#+title: Notes on ${author editor}, ${title}"))
```

This is the only thing stopping me switching from org-roam-bibtex currently. Is this functionality in the plan? or is it easy to hack it myself before it is added officially?

**Comment by RNAer** [comment]
I just realize that I need to set `bibtex-actions-notes-paths` to make `bibtex-actions-open-notes` work. The above question is no longer a problem, though it would be great if there is a config option to allow a prefix of time slug for file name like org-roam.

Another thing related is that I previously set `bibtex-actions-file-open-external` as the open function so that I can open pdf files with system app; otherwise, the pdf would be opened inside emacs. However, it gives me error running `bibtex-actions-open-notes` to create a new notes; I have to set `bibtex-actions-file-open-function` back to the original `find-file` . Is there a way to overcome?

**Comment by bdarcus** [comment]
> it would be great if there is a config option to allow a prefix of time slug for file name like org-roam.

> However, it gives me error running bibtex-actions-open-notes to create a new notes; I have to set bibtex-actions-file-open-function back to the original find-file . Is there a way to overcome?

It's not ideal, but if you use embark, you can access the external open command via embark-act.

I'll take another look at that code.

I'm open to enhancing the default note function, but it's not a high priority ATM.

Any reason you can't just use the orb function?

**Comment by RNAer** [comment]
Thanks! I guess I don't use orb because I don't want the heavy dependencies of orb and I don't use helm/ivy.

I am not sure how to access external open cmd via embark-act. The current options (below) do not work. Not super familiar with embark - How do I need to set the contextual commands for the cite following actions?
![image](https://user-images.githubusercontent.com/1000056/135713661-6f08c036-c872-43fe-b4b0-63e3ad313356.png)

**Comment by bdarcus** [comment]
> Thanks! I guess I don't use orb because I don't want the heavy dependencies of orb and I don't use helm/ivy.

Yeah, same here :-)

> I am not sure how to access external open cmd via embark-act. The current options (below) do not work. Not super familiar with embark - How do I need to set the contextual commands for the cite following actions? ![image](https://user-images.githubusercontent.com/1000056/135713661-6f08c036-c872-43fe-b4b0-63e3ad313356.png)

See at the end of this section:

https://github.com/bdarcus/bibtex-actions#files-file-association-and-file-field-parsing

You invoke `embark-act` on the file candidates, after you select the references.

**Comment by bdarcus** [comment]
Probably ideally we could use a new `bibtex-actions-file-open-notes-org-roam`, that use org-roams' template support?

**Comment by RNAer** [comment]
Supporting org-roam template would be great. My workflow is usually creating a note for every literature reading and then synthesize multiple notes into a bigger piece of summary - the standard org-roam process.  Time slug is only for naming consistency; I can live without it :)

I am not sure if I miss anything, but I set up embark as in your readme file and still can't get it work to open pdf with external app. I checked `bibtex-actions-open-library-files` code; it plainly calls `bibtex-actions-file-open-function` that I can't change for the above reason in the thread. I also looked at `bibtex-actions-file-extension` but it seems not relevant. Would you care to elaborate more? Much appreciated!

**Comment by bdarcus** [comment]
If you have `bibtex-actions-file-open-prompt` set to `t`, and run `bibtex-actions-open-library-files`, you should see something like this from `embark-act`.

![image](https://user-images.githubusercontent.com/1134/135719177-058127cf-8689-458a-a348-b64d3ff8a0c1.png)

Oh, and you have to have consult installed, come to think of it. In my case `x` will open the file(s) externally.

**Comment by bdarcus** [comment]
I will add, however, that we recently rewrote all the open functionality to do this internally, and to remove the bibtex-completion dependency there.

The good thing is that is we now have a lot more flexibility.

The bad is that flexibility requires choices.

**Comment by RNAer** [comment]
> I will add, however, that we recently rewrote all the open functionality to do this internally, and to remove the bibtex-completion dependency there.
> 
> The good thing is that is we now have a lot more flexibility.
> 
> The bad is that flexibility requires choices.

It is always a trade-off. Personally I believe flexibility but with a sensible default is the way.

> If you have `bibtex-actions-file-open-prompt` set to `t`, and run `bibtex-actions-open-library-files`, you should see something like this from `embark-act`.
> 
> ![image](https://user-images.githubusercontent.com/1134/135719177-058127cf-8689-458a-a348-b64d3ff8a0c1.png)
> 
> Oh, and you have to have consult installed, come to think of it. In my case `x` will open the file(s) externally.

Yes, this is what I did, but it doesn't work for me. And I don't have keybindings showing up as in your upper part of the screenshot. Here is my setting:
```

    (use-package consult
      :ensure t
      :demand t
      :bind (("M-g o" . consult-outline)
             ([remap goto-line] . consult-goto-line)
             ;; prefix your search with ‘b’ for buffer, ‘f’ for file, or ’m’ for bookmark.
             ([remap switch-to-buffer] . consult-buffer)
             ("<help> a" . consult-apropos)
             ("M-y" . consult-yank-pop)
             ("M-s g" . consult-grep)
             ("M-s G" . consult-git-grep)
             ;; M-s bindings (search-map)
             ;; Isearch integration
             ("M-s e" . consult-isearch)
             :map isearch-mode-map
             ("M-e" . consult-isearch)    ;; orig. isearch-edit-string
             ("M-s e" . consult-isearch)  ;; orig. isearch-edit-string
             ("M-s l" . consult-line)     ;; needed by consult-line to detect isearch
             ("M-s L" . consult-line-multi)  ;; needed by consult-line to detect isearch
             ("M-s m" . consult-multi-occur))
      :custom
      (completion-in-region-function #'consult-completion-in-region)
      :config
      ;; use consult-completing-read for enhanced interface
      (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple))


    (use-package embark
      :ensure t
      :bind (("C-." . embark-act) ;; type @ to switch to keybinding
             ("C-;" . embark-dwim)
             ("C-h B" . embark-bindings))
      :custom
      (embark-prompter 'embark-completing-read-prompter)
      (embark-indicators '(embark-minimal-indicator
                           embark-highlight-indicator
                           embark-isearch-highlight-indicator))
      (prefix-help-command #'embark-prefix-help-command))


        (use-package oc-bibtex-actions
          :bind (("C-c b" . org-cite-insert)
                 ("M-o" . org-open-at-point)
                 :map minibuffer-local-map
                 ("M-b" . bibtex-actions-insert-preset))

          :config
          (add-to-list 'embark-target-finders 'bibtex-actions-citation-key-at-point)
          (add-to-list 'embark-keymap-alist '(bib-reference . bibtex-actions-map))
          (add-to-list 'embark-keymap-alist '(citation-key . bibtex-actions-buffer-map))
          :custom
          (org-cite-insert-processor 'oc-bibtex-actions)
          (org-cite-follow-processor 'oc-bibtex-actions)
          (org-cite-activate-processor 'basic)
          (org-cite-global-bibliography '("~/org/zettelkasten/zotero.bib"))
          (bibtex-completion-bibliography '("~/org/zettelkasten/zotero.bib"))
          (bibtex-actions-notes-paths '("~/org/zettelkasten/"))
          (bibtex-actions-templates
           '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
            (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords keywords:*}")
            (note . "#+title: ${=key= id:15}")))
          ;; (bibtex-actions-file-open-function 'bibtex-actions-file-open-external)
          (bibtex-actions-file-open-prompt t)
          (bibtex-actions-filenotify-callback 'refresh-cache)
          (bibtex-actions-at-point-function 'embark-act))


```

**Comment by bdarcus** [comment]
> Yes, this is what I did, but it doesn't work for me. And I don't have keybindings showing up as in your upper part of the screenshot.

I'm using Doom's vertico module, which handles the configuration.

What commands do you see when running `embark-act` using, say, `find-file`?

**Comment by RNAer** [comment]
ok. I got to the bottom and solved it. The behavior you referred to depends on `embark-consult` package besides the individual `embark` and `consult`. That package defines `(define-key embark-file-map "x" #'consult-file-externally)`. 

Do you have the problem to cancel half-typed command with `bibtex-actions`? I met across a few where I can't cancel using `C-g`, such as in the middle of opening a file, search referenece, etc.

**Comment by carlosperezm** [comment]
> Do you have the problem to cancel half-typed command with `bibtex-actions`? I met across a few where I can't cancel using `C-g`, such as in the middle of opening a file, search referenece, etc.

I am having the same issue with `C-g`, is that a known limitation or should be reported separately?

**Comment by bdarcus** [comment]
> I am having the same issue with `C-g`, is that a known limitation or should be reported separately?

IDK.

The way to test is to see if it happens in more than one completion system; for example, selectrum and Vertico.

**Comment by RNAer** [comment]
I use selectrum but not vertico, so I can confirm `C-g` is a problem with bibtex-actions working with selectrum.

**Comment by carlosperezm** [comment]
> The way to test is to see if it happens in more than one completion system; for example, selectrum and Vertico.
I am using Vertico with the biblio doom module PR and see that
> In Vertico, on my system, I can just use `ESC` to exit.
As you said, this works, but for consistency with the rest of Emacs, `C-g` should also work for exiting. Unfortunately my elisp skills are not yet there to suggest why is that the case. Maybe you need to bind `C-g` somewhere to make it work?

**Comment by bdarcus** [comment]
No.

That's controlled by the vertico module, presumably, so I'm not going to attempt to override that.

**Comment by carlosperezm** [comment]
> No.
> 
> That's controlled by the vertico module, presumably, so I'm not going to attempt to override that.
> 
> If you want to change that, you should probably do it in your personal config, globally?

Thanks for the explanation. As I said, I am not familiar with the details of the modules. It is just that when I use vertico in other contexts (e.g find file with `SPC` `SPC` in Doom) it is possible to escape it with `C-g`.

In any case, it is not a major problem, just wanted to comment in case it was not noted before. Thanks for the great package! :-)

**Comment by bdarcus** [comment]
> It is just that when I use vertico in other contexts (e.g find file with `SPC` `SPC` in Doom) it is possible to escape it with `C-g`.

Oh, in that case I'll look into it.

I just don't see how there could be that conflict, given nothing here attempts to impact that.

Except, maybe it's consult-completing-read-multiple??

**Comment by bdarcus** [comment]
> ... maybe it's consult-completing-read-multiple?? You can test that (I'm not near a computer ATM) using `describe-face`.

I just confirmed this is in fact the case. 

I'm not sure if it's a bug or not, but you could ask at the consult project?

**Comment by carlosperezm** [comment]
> > ... maybe it's consult-completing-read-multiple?? You can test that (I'm not near a computer ATM) using `describe-face`.
> 
> I just confirmed this is in fact the case.
> 
> I'm not sure if it's a bug or not, but you could ask at the consult project?

This is now solved in Consult! :smile:
