### ISSUE TITLE
C-g does not quit in vertico mode

### ISSUE THREAD

**Issue by titaniumbones** [bdarcus/bibtex-actions#320]
**Describe the bug**
When  using `oc-cite-insert` with bibtex-actions as citation insert processor, and Vertico enabled, typing `c-g` does not exit the minibuffer.  

**To Reproduce**
1. Enable vertico-mode and set org-cite-insert-procssor to bibtex-actions
2. run the standard use-package directive from the README
3. at the Vertico prompt, do not select any citations; instead type C-g
4. Vertico will not exit; instead, prompt remains active.  C-return will exit, however. 

**Expected behavior**
In general, I would expect C-g to get me out of whatever I'm doing. THis should be the case here too. 

I'm not sure if the issue is with Vertico, org-cite, or bibex-actions, but I'm not seeing this problem with other vertico-mediated actions.

**Emacs version:**
28.0.50, recent

**Additional context**
Not sure if this is maybe a design choice or if it's really a bug.  To me it feels bug-like.

**Comment by bdarcus** [comment]
It was a bug, now fixed, in consult (specifically, in `consult-completiing-read-multiple`, because of a change in Emacs 28).

https://github.com/bdarcus/bibtex-actions/issues/317#issuecomment-933867451
