### ISSUE TITLE
Action does not work

### ISSUE THREAD

**Issue by liebkne** [bdarcus/bibtex-actions#34]
Hi, thanks for the package. 

I found that actions in `bibtex-actions-open` do not work. Below is my setup.

<details>

;; -*- lexical-binding: t; -*-

(setq straight-use-package-by-default t
      straight-check-for-modifications nil
      straight-vc-git-default-clone-depth 1)

;; straight.el
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(defun straight-update-all ()
  (interactive)
  (straight-pull-all)
  (straight-rebuild-all))

(setq use-package-verbose nil
      use-package-enable-imenu-support t
      use-package-always-defer t)
(straight-use-package 'use-package)

(defvar bibtex-base "~/org/bibliography/")
(defvar bibtex-pdf-directory (expand-file-name "pdf/" bibtex-base))
(defvar bibtex-note-directory (expand-file-name "papers/" bibtex-base))
(defvar bibtex-bibliography-list `(,(expand-file-name "references.bib" bibtex-base)))

(use-package bibtex-completion
  :init
  (use-package biblio
    :bind (:map biblio-selection-mode-map
                ("n" . biblio--selection-next)
                ("p" . biblio--selection-previous))
    :init (setq biblio-download-directory bibtex-pdf-directory))

  (setq bibtex-completion-cite-prompt-for-optional-arguments nil
        bibtex-completion-bibliography bibtex-bibliography-list
        bibtex-completion-library-path bibtex-pdf-directory
        bibtex-completion-notes-path bibtex-note-directory
        bibtex-completion-display-formats '((t . "${year:4}\t${author:28}\t${title:*}"))
        bibtex-completion-pdf-open-function #'bibtex-completion-pdf-open-external)

  (with-eval-after-load 'org-ref-helm-bibtex
    (setq bibtex-completion-display-formats '((t . "${year:4}\t${author:28}\t${title:*}"))))

  :config
  (defun bibtex-completion-pdf-open-external (file)
    (save-window-excursion
      (async-shell-command
       (format "open %s" (shell-quote-argument file))))))

(use-package bibtex-actions
  :straight (:host github :repo "bdarcus/bibtex-actions")
  :demand t
  :after (:any org latex)
  :config
  (setf (alist-get 'bibtex embark-keymap-alist) 'bibtex-actions-map)
  (with-eval-after-load 'org-ref
    (define-key org-mode-map [remap org-ref-insert-link] #'bibtex-actions-insert-key)))

(use-package selectrum
  :hook (after-init . selectrum-mode)
  :bind (("C-x C-z" . selectrum-repeat))
  :init (setq selectrum-max-window-height 7))

(use-package prescient
  :hook ((after-init . prescient-persist-mode))
  :init
  (use-package company-prescient
    :hook (global-company-mode . company-prescient-mode))

  (use-package selectrum-prescient
    :hook (selectrum-mode . selectrum-prescient-mode)))

(use-package consult
  :demand t
  :after selectrum
  :bind (("M-\"" . consult-complex-command)
         ("C-x b" . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x 5 b" . consult-buffer-other-frame)
         ("C-x r j" . consult-register)
         ("C-x r l" . consult-bookmark)
         ("C-s" . consult-line)
         ("C-c a" . consult-git-grep)
         ("C-c i" . consult-imenu)
         ("C-c I" . consult-project-imenu)
         ("M-y" . consult-yank-pop)
         ("M-g m" . consult-mark)
         ("M-g k" . consult-global-mark)
         ("M-g o" . consult-outline)
         ("M-g f" . consult-find)
         ("M-g e" . consult-error)
         ("M-s m" . consult-multi-occur)
         ("<help> a" . consult-apropos))

  :init
  (setq consult-async-min-input 1
        consult-ripgrep-command "rg --null --line-buffered --color=ansi --max-columns=1000 --no-heading --line-number . -e ARG OPTS")

  (setq consult-preview-key nil
        consult-config '((consult-line :preview-key any)))

  (setq xref-show-xrefs-function #'consult-xref
        xref-show-definitions-function #'consult-xref))

(use-package embark
  :demand t
  :after consult
  :bind (("C-z" . embark-act)))

(use-package embark-consult
  :demand t
  :after (embark consult)
  :hook (embark-collect-mode . embark-consult-preview-minor-mode))

</details>

When I call `embark-act` (<kbd>C-z</kbd> in my case) and `e` which should call `bibtex-actions-open-notes`, nothing happens and minibuffer exits. A message is printed at the same time: `Done (re)loading bibliography. [2 times]`

However, when I call `bibtex-actions-open-notes` directly and press <kbd>Enter</kbd>, it works fine.

The problem happens when using other actions too.

All package are using the latest master version on github.

**Comment by bdarcus** [comment]
Thanks!

Does this happen with all the "open" commands for you?

It does work fine on my system.

I wonder if you could try using one of these selectrum test scripts and see if it works there?

https://github.com/raxod502/selectrum/tree/master/test

I just then eval buffer on:

``` elisp
(load "~/Code/bibtex-actions/bibtex-actions.el")
(setq bibtex-completion-bibliography "~/org/bib/academic.bib")

(require 'embark)
(setf (alist-get 'bibtex embark-keymap-alist) 'bibtex-actions-map)
```

**Comment by bdarcus** [comment]
With the possibility this might somehow be related to 3 above, can you try updating selectrum and embark? They both pushed a change that might address this.

**Comment by bdarcus** [comment]
Update: I was able to reproduce the behavior on my setup.

Try again by first updating the packages, and then hitting tab on your selection before you invoke `embark-act`.

If that fixes the problem, let me know, as it's basically a UI issue with selectrum.

**Comment by liebkne** [comment]
Sorry for being late.

I've tested with the latest packages stack and it seems works fine. Thank you for digging into this!

**Comment by bdarcus** [comment]
This is related to an issue I have open at selectrum to further improve multi selection for use cases like this. Hopefully there will be a PR soon that we can test.
