### ISSUE TITLE
include org-noter reference

### ISSUE THREAD

**Issue by fab6** [bdarcus/bibtex-actions#348]
Hi,

I am very new to `bibtex-actions` and would like to adapt my vertico-consult-setup-bibtex-actions-org-roam setup with the options for notes...

Before I had a working spacemacs helm/helm-bibtex/org-ref/org-roam-bibtex setup

Before I had following template:
```elisp
  (setq bibtex-completion-notes-template-multiple-files
        (concat
         "#+TITLE: ${title}\n"
         "#+ROAM_KEY: cite:${=key=}\n"
         "* TODO Notes\n"
         ":PROPERTIES:\n"
         ":Custom_ID: ${=key=}\n"
         ":NOTER_DOCUMENT: %(orb-process-file-field \"${=key=}\")\n"
         ":AUTHOR: ${author-abbrev}\n"
         ":JOURNAL: ${journaltitle}\n"
         ":DATE: ${date}\n"
         ":DOI: ${doi}\n"
         ":URL: ${url}\n"
         ":KEYWORDS: ${keywords}\n"
         ":Type: \n"
         ":Topics: \n"
         ":END:\n\n"
         "* ${title}\n"
         "** Initial Questions\n"
         "** Structure\n"
         "** Slides\n"
         "** Interesting Aspects\n"
         "** Open Questions\n"
         "** References\n"
         )
        )
````
This work quite nice in combination with org-noter.

Now I am using:
```elisp
    (setq bibtex-actions-templates
          '((main . "${author editor:30}     ${date year issued:4}     ${title:48}")
            (suffix . "          ${=key= id:15}    ${=type=:12}    ${tags keywords:*}")
            (note . "#+title: Notes on ${author editor}, ${title}")))
    (setq bibtex-actions-notes-paths '("~/02_UoW_sciebo/00_Org/00_Roam/03_LIT_Notes/"))
    (setq bibtex-actions-file-note-org-include '(org-id org-roam-ref))
```

which results in:
```org
:PROPERTIES:
:ROAM_REFS: @powersLectureNotesFundamentals2014
:ID:   AC58E97A-4A54-4B0A-8C0E-6DB77707563E
:END:
#+title: Notes on Powers, Lecture Notes on Fundamentals of Combustion

Mein erster Test mit bibtex-actions
```
I am not sure yet how to include org-noter reference to it.

Maybe there is another way to achieve this!?

I also tried setting:
```elisp
  (setq bibtex-actions-file-open-note-function 'orb-bibtex-actions-edit-note)
```
though this uses the org-roam-capture-templates and does not recognize the org-noter anymore.
The corresponding part looks like (the same as for `bibtex-completion-notes-template-multiple-files`):
```elisp
           ("Ln" "Literature Notes" plain
        "%?"
        :if-new (file+head "03_LIT_Notes/<%Y%m%d%H%M%S>_${slug}.org"
           "#+TITLE: ${title}
           ,#+ROAM_KEY: cite:@${citekey}
           ,#+ROAM_REFs: cite:@${citekey}
           ,#+ROAM_ALIAS: ${alias}
           ,#+ROAM_TAGS: tool
           * TODO Notes
           :PROPERTIES:
           :Custom_ID: ${citekey}
           :NOTER_DOCUMENT: %(orb-process-file-field \"${file}\")
           :AUTHOR: ${author-abbrev}
           :JOURNAL: ${journaltitle}
           :DATE: ${date}
           :DOI: ${doi}
           :URL: ${url}
           :KEYWORDS: ${keywords}
           :Type:
           :Topics:
           :END:
           * ${title}
           ** Initial Questions
           ** Structure
           ** Slides
           ** Interesting Aspects
           ** Open Questions
           ** References")
        :unnarrowed t)
```

Maybe someone has a hint for this?
Thanks in advance!

**Comment by bdarcus** [comment]
What should the value of the noter line look like?

**Comment by fab6** [comment]
It would basically be the file path as I used it, e.g.:
```
:NOTER_DOCUMENT: /Users/fbraenns/03_LIT/ZOTERO/ZOTERO_zotfile/02_FIRE_THEORY/01_BOOKS/Vilyunov_Zarko_1989_Ignition of Solids.pdf

```

**Comment by bdarcus** [comment]
I don't know how general a solution this would be, and haven't tested it, but you can try editing the note template to include the `${file}` variable?

FWIW, if you use the ORB note function instead, you will be using bibtex-completion as the backend there.

**Comment by fab6** [comment]
Ah, ok, it seems that there is actually no need for `orb` but just a more extended `note` setup... it seems. I will try it and let you know.
Thank you very much!

**Comment by fab6** [comment]
So one option without orb could be
```elisp
            (note . "#+title: Notes on ${title}\n* ${title}\n :PROPERTIES:\n :Custom_ID: ${=key=}\n :cite: ${=key=}\ :authors: ${author}\n :journal: ${journaltitle}\n :NOTER_DOCUMENT: ${file}\n :Date: ${date}\n :DOI: ${doi}\n :URL: ${url}\n :KEYWORDS: ${keywords}\n :Type: -\n :Topics: -\n :END:\n* ${title}\n** Initial Questions\n** Structure\n** Slides\n** Interesting Aspects\n** Open Questions\n** References\n"
```
which results in 
![image](https://user-images.githubusercontent.com/3047695/139533806-7f70a6f8-6330-4491-a648-74981cac5c40.png)
... with obviously too many titles... and I understand that the properties could also be directly in the head.

**Comment by bdarcus** [comment]
> I understand that the properties could also be directly in the head.

While that's true in general, the buillt-in note templates aren't designed for configuring the header. So what you have is the right option here, with the obvious limitation it doesn't work ideally if what field value is nil.

Perhaps at some point we can add an option for capture templates, though I don't have any experience with it.

**Comment by fab6** [comment]
ok, a bit more fine tunig results in
```elisp
 (note . "#+title: Notes on ${title}\n\n\n* ${title}\n :PROPERTIES:\n  :Custom_ID:  ${=key=}\n  :cite: [cite:@${=key=}]\n  :authors: ${author}\n  :journal: ${journaltitle}\n  :NOTER_DOCUMENT: ${file}\n  :Date: ${date}\n  :DOI: ${doi}\n  :URL: ${url}\n  :KEYWORDS: ${keywords}\n  :Type: -\n  :Topics: -\n :END:\n\n** Initial Questions\n** Structure\n** Slides\n** Interesting Aspects\n** Open Questions\n** References\n"
```

So that would mean that I do not need any `orb` at all.

now there is a new one... only the German umlaut is not so nice...
```
  title		= {W\"arme- und Stoff\"ubertragung},
```
![image](https://user-images.githubusercontent.com/3047695/139534154-0f49b74d-b411-41bb-afb0-e7a0e687451c.png)

I will check what I can find.

Thank you very much again!

**Comment by fab6** [comment]
Ok, I just read your comment above, thank you

**Comment by bdarcus** [comment]
> only the German umlaut is not so nice...

I'd guess that might currently be an issue if not using unicode, and instead using the latex strings.

I can look into that.

**Comment by fab6** [comment]
thank you very much!

**Comment by bdarcus** [comment]
@joostkremers - is there something special I need to do get a bibtex field whose content is this to output unicode?

```bib
  title		= {W\"arme- und Stoff\"ubertragung},
```

I'm just using `parsebib-parse` with the default display value.

**Comment by joostkremers** [comment]
> @joostkremers - is there something special I need to do get a bibtex field whose content is this to parse it into unicode?
> 
> ```
>   title		= {W\"arme- und Stoff\"ubertragung},
> ```
> 
> I'm just using `parsebib-parse` with the default display value.

Unfortunately, parsebib cannot do such a conversion. If there is some functionality in Emacs that can do it, it should be possible to plug it into parsebib, but I'm not aware of anything like that.

**Comment by bdarcus** [comment]
> Unfortunately, parsebib cannot do such a conversion. If there is some functionality in Emacs that can do it, it should be possible to plug it into parsebib, but I'm not aware of anything like that.

OK, thanks.

Is it best/reasonable to recommend users like @fab6 standardize on unicode in their data in 2021 then?

**Comment by joostkremers** [comment]
> Is it best/reasonable to recommend users like @fab6 standardize on unicode in their data in 2021 then?

I definitely think it's best, and I also think it's reasonable, given the fact that every modern operating system and every modern TeX system supports Unicode. Even pdflatex understands Unicode with the `inputenc` package. Plus, Emacs' Unicode support is excellent.

Additionally, biblatex offers more features than BibTeX, not least of which is the fact that it gets sorting right for languages other than English. (German just happens to work because it doesn't treat ä, ö, ü and ß as separate letters and the LaTeX commands for them use the letters they are alphabetised as.)

Plus, IMHO it's much nicer to write `"Wärme- und Stoffübertragung"`.

> What do you do for example?

I use UTF-8 exclusively. I don't see any reason not to, to be honest.

**Comment by fab6** [comment]
yes, good point, I am doing it now ... biblatex as well and did not recognized the option in zotero betterbibtex export yet.
Thank you again for the help!
