### ISSUE TITLE
drop Emacs 26.3?

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#46]
This is a new package without wide usage ATM. And Ubuntu's next release in a few weeks will.move to 27.1.

Thoughts?

**Comment by mtreca** [comment]
Might be a bit too early I think. Many popular packages still support Emacs 25. Are there any features of this package that explicitely require Emacs > 26.3 ?

**Comment by bdarcus** [comment]
No. I'll close then :-)
