### ISSUE TITLE
format-entry widths

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#67]
#66 fixed one problem, but introduced another minor one.

The default suffix template has `${tags:*}`, which should extend the last column to the end.

But it's truncated much earlier (if you see below, it seems like the tags are truncated at about 27 characters).

![Screenshot from 2021-04-13 12-41-19](https://user-images.githubusercontent.com/1134/114589432-a6d40c80-9c55-11eb-94ef-3060c89c5536.png)

Must be because we no longer assume a single template.

Here's what I see in `ielm`:

``` elisp
ELISP> (bibtex-actions--process-display-formats bibtex-actions-template-suffix)
((t "          ${=key=:15}    ${=type=:12}    ${tags:*}" . 45))
ELISP> bibtex-completion-display-formats-internal
((t "${author:36} ${title:*} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7}" . 53))
```

**Comment by bdarcus** [comment]
Can you two take a look at this @jethrokuan @nobiot?

If you use multiple templates in org-roam, it will have the same problem.

**Comment by nobiot** [comment]
Is this "bug" relevant for the latest commit available from MELPA? Sorry I am a bit confused about how to contribute here.

By the looks of the current source code, these lines use the templates to produce a long string of text for each candidate.
https://github.com/bdarcus/bibtex-actions/blob/main/bibtex-actions.el#L143-L152

If the suffix has issue of truncating too early, then it's the issue of the function `bibtex-actions--format-entry` not correctly processing `${tags:*}"` for suffix -- perhaps the asterisk is not properly interpreted? Char length 27 appears to be an outcome of 15 + 12, ignoring "*".

I could look at the runtime in `edebug` if I know which commit/branch I can reproduce the issue with.

**Comment by bdarcus** [comment]
It's apparent in the latest MELPA release/main branch.

For context, I forked the bibtex-completion-init-entry function, and did not touch the logic of it.

So I'm assuming the issue is something to do with the distinction between the total width for the intended table, and the widths for each template.

TIA!

**Comment by bdarcus** [comment]
As in, it works as expected if there is only one template/section.

Bibtex-completion and its ivy and helm frontend were designed around that assumption.

**Comment by nobiot** [comment]
I'd debug focusing in this part:

           (truncate-string-to-width
            field-value
            (if (> field-width 0)
                field-width
              (- width (cddr format)))

The `width` var is calculated in the calling function; 34% of the frame width. If * is translated to zero, perhaps `(- width (cddr format)` yields an unexpected result.

Can't debug now (working) but I'm curious ;)

I'm assuming that having 2 templates is not an issue -- it may be, but it does not look to be the case so far. I might well be wrong on that, of course.

**Comment by bdarcus** [comment]
Interestingly, if I change the widths like so, the rendering is closer to expectation.

``` elisp
         (main-width (truncate (* (frame-width) 0.65)))
         (suffix-width (truncate (* (frame-width) 0.55))))
```

That clearly doesn't add up, because the sum is then greater than the frame-width, but the string does not extend beyond the frame.

Aside: I added those lines because earlier the table was extending beyond the frame, which caused rendering problems in some completion systems.

**Comment by bdarcus** [comment]
I opened a branch on #87 to figure this out.
