### ISSUE TITLE
add caching of bib candidates

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#69]
Thanks for this nice package!  I gave it a try and it worked smoothly for me.

I have a relatively large BibTeX file with over 1,000 entries (and 10,000 lines) and I have been using `ivy-bibtex`.  The `bibtex-ctions` takes a noticeable time to read/load the BibTeX file every time, while `ivy-bibtex` takes a noticeable time only the first time (assuming that the BibTeX file has not been changed).  I guess it is because `ivy-bibtex` somehow caches the BibTeX file that has been read the first time.  Thus, IMHO, it would be great if `bibtex-actions` contains a similar caching mechanism.

_Originally posted by @wenjie2wang in https://github.com/bdarcus/bibtex-actions/discussions/68_

**Comment by bdarcus** [comment]
I agree we should add this @wenjie2wang. I'm just not sure how ATM.

[Here's the code](https://github.com/tmalsburg/helm-bibtex/blob/9e76316278c5722660257eadfae6a901aa8225fe/ivy-bibtex.el#L128) in `ivy-bibtex`.

Once we get this working, we need to go back to #41.

**Comment by bdarcus** [comment]
@wenjie2wang any chance you can post your bib file so I can test?

**Comment by bdarcus** [comment]
@wenjie2wang can you please see here? 

https://github.com/bdarcus/bibtex-actions/pull/70#issuecomment-817148742

It should be working here.

**Comment by wenjie2wang** [comment]
Thanks for your quick response!  FYI, my bib file is available at <https://gitlab.com/wenjie2wang/bibrary/-/raw/master/bib/index.bib>.

**Comment by bdarcus** [comment]
OK, thanks.

I think I actually know what's going on. Will check in a bit.

**Comment by bdarcus** [comment]
I just loaded your file, and every time I load a command, there's a pause, but it's certainly less than a second. 

What do you mean by "noticeable time"?

**Comment by bdarcus** [comment]
That said, I do think we've identified a performance bottleneck, that when fixed should address this.

**Comment by wenjie2wang** [comment]
> I just loaded your file, and every time I load a command, there's a pause, but it's certainly less than a second.
> 
> What do you mean by "noticeable time"?

Thanks, @bdarcus !  This is what I mean by "noticeable time".  There is always a noticeable pause after `M-x bibtex-actions-open`.  In contrast, `M-x ivy-bibtex` is able to respond instantly after the first run.  I made a gif for your reference.  
![Peek 2021-04-10 12-23](https://user-images.githubusercontent.com/11081955/114277118-e43b5e80-99f7-11eb-9def-274516e44b42.gif)

**Comment by bdarcus** [comment]
OK, thanks much! That's what I see.

Not terrible, but I'd like performance to be consistently very good to excellent.

If you see the linked PR, I've figured out what causes this, but not yet why.

**Comment by bdarcus** [comment]
So I've been digging into this, and I can't see an obvious way to improve this.

We have two functions that generate this UI:

1. `bibtex-completion-candidates`: this one is cached, and is fast
2. `bibtex-actions--get-candates`: this one is not cached, and is slower, because it does the display formatting

Because of how completing-read is designed, I need 2, though (it doesn't have any notion of display transformers as in helm and ivy).

Ideally, I'd like to be able to replace the candidate string in 1, with the output of 2. That would allow all of the display data to be cached.

But I haven't figured out how I can do that.

@tmalsburg - any thoughts?

**Comment by bdarcus** [comment]
I've opened a linked pr that adds a cache. A hook could still be useful, but if this works, it's a small enough addition that I'm happy to merge it.
