### ISSUE TITLE
Add completion-at-point

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/bibtex-actions#91]
## Overview

Perhaps at-point completion would be more efficient for the more narrow task of citation and/or key insertion when writing, particularly for the [forthcoming new org-mode citation support](https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00227.html), something like you see in the Zettlr markdown editor?

![Screenshot from 2021-04-22 04-07-16](https://user-images.githubusercontent.com/1134/115712598-f647c600-a342-11eb-9401-5aebfb56c4bf.png)

Don't really know anything about this, but thought of it because of this new package.

https://github.com/minad/corfu

And there's, of course, `company`.

If the feature makes sense, I may experiment with it. But a PR would be even better!

EDIT: see [this comment](https://www.reddit.com/r/emacs/comments/msx6s1/elpa_corfu_completion_overlay_region_function/guyney5?utm_source=share&utm_medium=web2x&context=3) for limitations and possibilities, in particular the note you can make it possible move from at-point to the minibuffer.

## Possible implementation approach

If I understand how the API works, we'd probably want something like the following functions:

Edited based on discussion in comments.

1. `bibtex-actions-complete-key-at-point` (as with Zettlr screenshot above; the easiest and most general, and will cover 90% or so of need, and work with both org and pandoc syntax)
2. `bibtex-actions-complete-citation-at-point` (specifically for new org cite support, which will have more complex syntax and features; see #108)

## Org-cite syntax

Here's the new syntax:

``` 
 [cite/style:common prefix ;prefix @key suffix; ... ; common suffix]
```
Goal is to make citation entry really smooth and efficient, then.

So I'm thinking user experience would be something like:

- type `[c` and that can auto-complete to `[cite`
- type `/` and presents pop-up options of styles, completes that, and places point after this `[cite/style:`
- type `@` and list of citation keys pops up for selection (this seems the only piece that would be necessary)
- etc.

**Comment by minad** [comment]
I guess many people would like such a functionality. If you have Corfu installed it is pretty simple to get something running. However this won't work with Company since as far as I know, Company does not provide a completion in region function. Company only supports completion at point functions.

~~~ elisp
(defun bibtex-complete ()
  (interactive)
  (pcase (preceding-char)
    (?@ (completion-in-region (- (point) 1) (point) '("@key1" "@key2" "@key3" "@key4")))
    (?[ (completion-in-region (- (point) 1) (point) '("[ref1:" "[ref2:" "[ref3:" "[ref4:")))
    (_ (user-error "No bibtex completion")))))

(global-set-key "\C-q" #'bibtex-complete)
~~~

**Comment by bdarcus** [comment]
Thanks @minad!

You can probably tell I'm not clear on the distinction between `completion-in-region` and `completion-at point`!

>  I think capf and completion-in-region are not mutually exclusive. If you want to use TAB completion, capf is the way to go and if you want to provide separate commands completion-in-region is more appropriate.

I think for this case, we probably just need this for a single command: to insert a citation, per the screenshot up top.

So maybe we should then target capf?

> Both approaches can share the completion table and the candidate generation code.

... and share with the `completing-read` function too; right?

As in, we'd want to adapt the table that `bibtex-read` uses (the candidates come from `bibtex-actions--format-candidates`) to add a propertized string targeted to this UI?

**Comment by minad** [comment]
> So maybe we should then target capf?

Caps are functions registered in the list `completion-at-point-functions`. Each function in this list is tried in order if it provides completion. Many modes already provide such a function and the first one will win. It will probably work well if you use a trigger character like @, such that your capf function takes control only if the character before the point is @. 

> ... and share with the completing-read function too; right?

Yes, the completion table can be reused between capf, completion-in-region and minibuffer-completion/completing-read. This is kind of neat about the completion design.

> As in, we'd want to adapt the table that bibtex-read uses (the candidates come from bibtex-actions--format-candidates) to add a propertized string targeted to this UI?

I don't understand what you mean by that.

**Comment by minad** [comment]
I believe Corfu works reasonably well with long candidates. But in case you want to use shorter candidates there is no other way than writing a separate candidate formatter.

**Comment by bdarcus** [comment]
Added in #132.
